import { useState } from 'react';
import { challengePixels, targetPixels } from './models';
import { Feedback, Reasoning, Select, Task, Workbench, useWork, type ModeProps } from './shared';
function Grid({ label, values }: {
    label: string;
    values: string;
}) { return <section className="sw-record" aria-label={label}><h4>{label}</h4><div className="sw-grid">{values.split('').map((v, i) => <span className="sw-pixel" key={i} data-value={v} aria-label={`row ${Math.floor(i / 3) + 1} column ${i % 3 + 1}: ${v === '1' ? 'black 1' : v === '0' ? 'white 0' : 'not entered'}`}>{v === '1' ? 'Black 1' : v === '0' ? 'White 0' : 'Not entered'}</span>)}</div></section>; }
export default function PixelPost(props: ModeProps) { const w = useWork(props.onEvent); const [order, setOrder] = useState(''), [values, setValues] = useState(Array<string>(9).fill('')), [decoded, setDecoded] = useState(''), [decodedRevision, setDecodedRevision] = useState(-1), [repairRecord, setRepairRecord] = useState<number | null>(null), [challenge, setChallenge] = useState(false), [cell, setCell] = useState(''), [repair, setRepair] = useState(''), [repaired, setRepaired] = useState(false), [repairFeedback, setRepairFeedback] = useState(''), [cursor, setCursor] = useState(0); const edit = () => { w.edit(); setChallenge(false); setCell(''); setRepair(''); setRepaired(false); setRepairFeedback(''); }; const enter = (i: number, v: string) => { edit(); setValues(old => old.map((x, j) => j === i ? v : x)); }; return <Workbench title="Pixel Post" props={props} reveal={challenge ? 'repair' : w.valid ? 'challenge' : 'encode'} visual={<><Grid label="Original flag" values={targetPixels}/><Grid label="Values entered" values={values.map(v => v || '?').join('')}/>{decoded && <Grid label={decodedRevision === w.revision ? "Local reconstruction" : "Earlier local reconstruction"} values={decoded}/>} {challenge && <><Grid label="One value changed" values={repaired ? targetPixels : challengePixels}/></>}{repairRecord !== null && <section className="sw-record" aria-label="Retained repair record"><h4>{repaired && repairRecord === w.revision ? "Current repair record" : "Earlier successful repair"}</h4><p>Repair record: row 2, column 3 changed from black 1 to white 0.</p><Grid label="Retained repaired picture" values={targetPixels}/>{!(repaired && repairRecord === w.revision) && <p>This earlier repair is kept for comparison. It does not check the current draft.</p>}</section>}</>}><Task title="Encode in the shared order"><Select label="Reading order" value={order} onChange={v => { edit(); setOrder(v); }} options={[["columns", "Down each column first"], ["rows", "Top-left, across each row"]]}/><div className="sw-grid">{values.map((v, i) => <Select key={i} label={`Value row ${Math.floor(i / 3) + 1} column ${i % 3 + 1}`} value={v} options={[["1", "Black 1"], ["0", "White 0"]]} onChange={value => enter(i, value)}/>)}</div><div tabIndex={0} role="group" aria-label="Keyboard pixel cursor" onKeyDown={e => { if (['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', '0', '1'].includes(e.key)) {
    e.preventDefault();
    if (e.key === '0' || e.key === '1')
        enter(cursor, e.key);
    else
        setCursor(c => Math.max(0, Math.min(8, c + ({ ArrowLeft: -1, ArrowRight: 1, ArrowUp: -3, ArrowDown: 3 }[e.key] ?? 0))));
} }}><p>Cursor: row {Math.floor(cursor / 3) + 1}, column {cursor % 3 + 1}. Arrow keys move; 0/1 enters a value.</p><div className="sw-row"><button onClick={() => setCursor(c => (c + 1) % 9)}>Next cell</button><button onClick={() => enter(cursor, '1')}>Black at cursor</button><button onClick={() => enter(cursor, '0')}>White at cursor</button></div></div><button onClick={() => { if (values.some(v => v === '')) {
    w.check(false, 'Every square needs a value, including white squares.');
    return;
} setDecoded(values.join('')); setDecodedRevision(w.revision); const ok = order === 'rows' && values.join('') === targetPixels; w.check(ok, ok ? 'Your local reconstruction matches. Now inspect one changed value.' : order !== 'rows' ? 'Use the agreed top-left row order.' : 'Compare the grids in the agreed order to locate the first difference.'); }}>Decode my values</button><Feedback label="Encoding feedback">{w.feedback}</Feedback></Task>{w.valid && <Task title="Locate and repair"><button onClick={() => setChallenge(true)}>Open one value changed</button>{challenge && <><Select label="Repair cell" value={cell} onChange={v => { setCell(v); setRepaired(false); setRepairFeedback(''); }} options={values.map((_, i) => [String(i), `Row ${Math.floor(i / 3) + 1}, column ${i % 3 + 1}`])}/><Select binaryKeys label="Repair value" value={repair} onChange={v => { setRepair(v); setRepaired(false); setRepairFeedback(''); }} options={[["0", "White 0"], ["1", "Black 1"]]}/><button onClick={() => { const ok = cell === '5' && repair === '0'; setRepaired(ok); if (ok) setRepairRecord(w.revision); setRepairFeedback(ok ? 'You repaired row 2, column 3 to white 0. The flag matches again.' : 'Locate the changed square first, then use the original grid to choose its value.'); props.onEvent({ type: 'coach', cue: ok ? 'milestone' : 'retry' }); }}>Check repair</button><Feedback label="Repair feedback">{repairFeedback}</Feedback></>}</Task>}<Reasoning key={`${w.revision}-${cell}-${repair}`} ready={w.valid && repaired} onComplete={props.complete} onEvent={props.onEvent} claim="The shared key and row order put each value in its intended square. One changed value changes one square." limit="This picture was reconstructed locally; it was not sent to a remote person."/></Workbench>; }
