import type { WidgetCoach } from '../schema';
import type { MathWorkshopConfig } from './workshop-schema';
type AuthoredActivity = {
    activity: MathWorkshopConfig['activity'];
    lesson: string;
    card: number;
    title: string;
    setup: string;
    guide: string;
    kid: string;
    start: string;
    strategy: string;
    retry: string;
    milestone: string;
    complete: string;
};
export const mathWorkshopSources: readonly AuthoredActivity[] = [
    { activity: 'estimate-checkpoint', lesson: 'math-u02-l02', card: 3, title: 'Estimate Checkpoint', setup: 'Two acorn counts are 36,418 and 22,693. A sign claims their sum is 159,111. Round each count to the nearest thousand or ten thousand to check the sign.', guide: 'This acorn sign might have a counting mistake. Choose friendly numbers to check its size.', kid: 'I’ll round both counts, build an estimate, and compare it with the sign.', start: 'Check the sign', strategy: 'Compare the sizes of the two original counts and the claimed sum.', retry: 'Check your rounded counts, equation, and comparison of the sizes.', milestone: 'Use the work you have checked to decide whether the sign fits.', complete: 'You used an estimate to catch a result with the wrong size.' },
    { activity: 'acorn-rule-machine', lesson: 'math-u03-l02', card: 2, title: 'Acorn Rule Machine', setup: 'A seed machine follows one rule. The recorded pairs are 2 bags → 12 seeds, 4 bags → 24 seeds, and 7 bags → 42 seeds. Find the seeds for 5 bags and the bags for 54 seeds.', guide: 'A seed machine follows one rule every time. One matching row might fool us.', kid: 'I’ll test my rule on every row, then fill the missing spaces.', start: 'Test a rule', strategy: 'Compare each predicted output with its recorded output.', retry: 'Use all three recorded rows to check your rule, then use that rule for the missing entries.', milestone: 'Keep each checked result and compare it with the same rule.', complete: 'You checked a rule across the table and used it to extend the pattern.' },
    { activity: 'pack-use-rebuild', lesson: 'math-u05-l02', card: 2, title: 'Pack, Use, Rebuild', setup: 'Four packs hold 18 markers each; 15 markers are used. How many remain? Build the packs, then construct an equation with m for the remaining markers.', guide: 'Some markers were packed, then some were used. Our model needs both events in order.', kid: 'I’ll build the packs, show what was used, and check where the unknown belongs.', start: 'Build the marker story', strategy: 'Which amount must exist before we can remove used markers?', retry: 'Match the packs, used markers, and unknown to the current story.', milestone: 'Keep the checked quantities in your model for the next step.', complete: 'Your equations match both stories, even when the unknown moves.' },
    { activity: 'fraction-picnic', lesson: 'math-u06-l02', card: 3, title: 'Fraction Picnic', setup: 'There are eleven eighth-size sandwich pieces. Each equal-size whole outline has eight slots. Share all the pieces into two or three nonempty plates and record two different groupings.', guide: 'These sandwich pieces are all the same size. Can we share them in different groups without changing how much food there is?', kid: 'I’ll move the eighths, record two groupings, and compare their totals.', start: 'Arrange the picnic', strategy: 'Keep the eighth-size pieces together while you compare different groups.', retry: 'Check the piece size, total count, and how your groups compare with the saved records.', milestone: 'Use the records and the same pieces to compare your groupings.', complete: 'Your two sums describe the same eleven eighth-size pieces.' },
    { activity: 'bundle-the-fourths', lesson: 'math-u06-l03', card: 2, title: 'Bundle the Fourths', setup: 'Thirteen quarter-size tiles are beside four equal-size frames. Each frame holds four quarters. Bundle the pieces to name this amount in two ways.', guide: 'A whole can be packed with four fourths. Let’s see two ways to name the same pile.', kid: 'I’ll bundle the pieces into wholes, then unpack another mixed number to check the connection.', start: 'Bundle the pieces', strategy: 'How many equal pieces fill one whole?', retry: 'Count the fourths inside every whole before adding the loose pieces.', milestone: 'The pieces stayed the same. Only their grouping changed.', complete: 'You renamed both quantities without adding or losing any fourths.' },
    { activity: 'decimal-exchange-mat', lesson: 'math-u08-l03', card: 3, title: 'Decimal Exchange Mat', setup: 'Round A is 0.48 + 0.36. Whole tiles cover one unit square, tenth strips cover ten hundredth cells, and small pieces cover one hundredth. Estimate, build, and trade equal values.', guide: 'Our pieces can trade places without changing their value. That can help us add and subtract.', kid: 'I’ll match the piece sizes, make equal trades, and write each result as a fraction and a decimal.', start: 'Open the exchange mat', strategy: 'An exchange needs ten smaller pieces for one piece in the next place.', retry: 'Check the value of each piece and the amount represented on the mat.', milestone: 'Compare the covered amount with your fraction and decimal records.', complete: 'Your fraction and decimal records describe the same remaining or combined amount.' },
    { activity: 'fence-the-garden', lesson: 'math-u10-l01', card: 2, title: 'Fence the Garden', setup: 'A rectangle has perimeter 34 m and length 11 m. Width is unknown. A reel holds 34 one-meter fence segments. Fence the known opposite sides, then share the remaining fence between the other sides.', guide: 'This fence must go around every edge of the garden. Two side lengths are missing.', kid: 'I’ll use fence for both known sides, share what remains, and check all four edges.', start: 'Fence the garden', strategy: 'Find the opposite side with the same length. It needs fence too.', retry: 'What must be true about opposite sides of a rectangle?', milestone: 'Read all four side labels to check your boundary.', complete: 'Your fence covers the complete boundary with equal opposite sides.' },
    { activity: 'triangle-inspection-desk', lesson: 'math-u11-l01', card: 3, title: 'Triangle Inspection Desk', setup: 'Inspect triangles A–D using side marks and angle measurements. A has three equal sides and angles 60°, 60°, 60°. B has exactly two equal sides and 45°, 45°, 90°. C has three unequal sides and 30°, 40°, 110°. D has exactly two equal sides and 40°, 70°, 70°.', guide: 'A triangle can have a side name and an angle name. Turning it won’t change its measurements.', kid: 'I’ll inspect the marks, give both kinds of names, and show my evidence.', start: 'Inspect the triangles', strategy: 'Use the printed measurements and matching marks, even when the triangle is tilted.', retry: 'Use side marks and angle measures to check every selected name.', milestone: 'Point to the marks that support your names.', complete: 'You used side and angle evidence, and rotation kept both classifications unchanged.' },
    { activity: 'graph-detective', lesson: 'math-u12-l02', card: 3, title: 'Graph Detective', setup: 'Three cases use a picture graph, a bar graph, and a fraction table. In the picture graph, one basket stands for 4 apples. Trail Group has two and a half baskets. How many apples did it pick?', guide: 'A picture can stand for more than one thing. Check the key before choosing a calculation.', kid: 'I’ll read the display, mark the data I need, and build one equation for each question.', start: 'Inspect the data', strategy: 'Read the display’s key and units before choosing an operation.', retry: 'Check which data the question needs, the operation, and the unit.', milestone: 'Keep the checked data and equation together as you explain this case.', complete: 'You used the display’s key, values, and units to answer each question.' },
];
export const mathWorkshopActivities: {
    lessonId: string;
    cardId: string;
    config: MathWorkshopConfig;
    coach: WidgetCoach;
}[] = mathWorkshopSources.map(a => ({
    lessonId: a.lesson, cardId: `${a.lesson}-c${a.card}`, config: { activity: a.activity }, coach: { startLabel: a.start, intro: [{ speaker: 'guide', pose: 'talk', text: a.guide }, { speaker: 'kid', text: a.kid }], reactions: { strategy: { pose: 'think', text: a.strategy }, retry: { pose: 'oops', text: a.retry }, milestone: { pose: 'talk', text: a.milestone }, complete: { pose: 'cheer', text: a.complete } } },
}));
export function mathWorkshopSpeechText(config: MathWorkshopConfig): string[] { const source = mathWorkshopSources.find(a => a.activity === config.activity); return source ? [source.title, source.setup] : []; }
