import type { Lesson } from '../schema';

export const unit01Lessons = [
  {
    id: 'reading-u01-l01',
    unitId: 'reading-u01',
    title: 'Read Accurately at a Good Pace',
    indicatorCodes: ['ELA.4.F.4.2'],
    intro: [
      { speaker: 'winnie', pose: 'talk', text: 'Fluent reading begins with getting the words right and understanding what they say.' },
      { speaker: 'winnie', pose: 'think', text: 'A useful pace is not a race; it gives your brain time to build meaning.' },
      { speaker: 'winnie', pose: 'talk', text: 'You can practice fluency while reading aloud or silently.' },
      { speaker: 'winnie', pose: 'cheer', text: 'Let’s combine accuracy, an appropriate pace, expression, and intonation so the message stays clear.' },
    ],
    learnCards: [
      {
        id: 'reading-u01-l01-c1',
        title: 'Accuracy protects the meaning',
        blocks: [
          { kind: 'text', text: 'Fluent readers read the words the author wrote. They notice a mistake, return to it, and reread the sentence so it makes sense.' },
          { kind: 'example', text: 'In “The tiny crab slipped under the striped shell,” changing crab to cap would change the picture, so an accurate reader checks the letters and rereads.' },
          { kind: 'tip', text: 'Use the sentence meaning and every letter in a word; do not guess from only the first sound.' },
        ],
      },
      {
        id: 'reading-u01-l01-c2',
        title: 'An appropriate pace fits the text',
        blocks: [
          { kind: 'text', text: 'Appropriate rate means reading smoothly enough to connect ideas while slowing down for challenging words, important details, or complex sentences.' },
          { kind: 'example', text: 'A reader might move steadily through “Rain tapped the roof,” then pause to unpack a sentence explaining how a rain gauge works.' },
          { kind: 'tip', text: 'Read meaningful groups of words instead of racing word by word or stopping after every word.' },
        ],
      },
      {
        id: 'reading-u01-l01-c3',
        title: 'Check fluency by checking meaning',
        blocks: [
          { kind: 'text', text: 'Build stamina by reading varied academic and personal texts aloud and silently for longer stretches, then explain what you understood.' },
          { kind: 'text', text: 'Written, oral, visual, digital, and interactive texts may combine words with maps, captions, images, or audio, so connect each part to the same message.' },
          { kind: 'example', text: 'After reading “Muddy paw prints crossed the porch, but the dog bed was empty,” infer what may have happened and cite “muddy paw prints” as evidence.' },
          { kind: 'tip', text: 'Use a three-line reflection labeled Accuracy, Pace, and Meaning/Evidence; this consistent format helps you create careful work.' },
          { kind: 'tip', text: 'For optional partner practice, take turns and listen actively before sharing one specific place that sounded clear; this lesson does not score anyone’s spoken reading.' },
        ],
      },
    ],
    workedExample: {
      title: 'Fluency check at the marsh boardwalk',
      steps: [
        'Preview the original passage: “Nia stepped onto the boardwalk. Beyond the reeds, a white egret lifted one wing, balanced, and dipped its beak into the shining water.”',
        'Read accurately by checking boardwalk, egret, and balanced instead of replacing them with easier-looking words.',
        'Use a steady pace, pause briefly at the comma, and slow down enough to picture the egret’s actions.',
        'Check comprehension by explaining that Nia sees an egret hunting in shallow water and cite the bird dipping its beak as evidence.',
      ],
    },
    quiz: {
      passThreshold: 8,
      pool: [
        {
          id: 'reading-u01-l01-q01',
          type: 'multiple-choice',
          prompt: 'Which description best explains fluent reading?',
          choices: [
            { id: 'a', text: 'Reading every text as fast as possible' },
            { id: 'b', text: 'Reading accurately at an appropriate pace with expression that supports meaning' },
            { id: 'c', text: 'Skipping unfamiliar words to keep moving' },
            { id: 'd', text: 'Memorizing a passage without thinking about it' },
          ],
          correctChoiceId: 'b',
          explanation: 'Fluency combines accuracy, appropriate pace, expression, and understanding.',
          conceptTag: 'reading-accuracy',
          reviewCardId: 'reading-u01-l01-c1',
        },
        {
          id: 'reading-u01-l01-q02',
          type: 'multiple-choice',
          prompt: 'A reader says “cost” instead of “coast”; which fluency skill needs attention?',
          choices: [
            { id: 'a', text: 'Accuracy' },
            { id: 'b', text: 'Volume' },
            { id: 'c', text: 'Page turning' },
            { id: 'd', text: 'Memorization' },
          ],
          correctChoiceId: 'a',
          explanation: 'Replacing coast with cost changes the word and can change the meaning.',
          conceptTag: 'reading-accuracy',
          reviewCardId: 'reading-u01-l01-c1',
        },
        {
          id: 'reading-u01-l01-q03',
          type: 'true-false',
          prompt: 'If a sentence stops making sense, rereading it accurately is a useful strategy.',
          choices: [
            { id: 'true', text: 'True — rereading can repair meaning' },
            { id: 'false', text: 'False — keep going without checking' },
          ],
          correctChoiceId: 'true',
          explanation: 'Rereading lets you correct a word and rebuild the sentence’s meaning.',
          conceptTag: 'reading-accuracy',
          reviewCardId: 'reading-u01-l01-c1',
        },
        {
          id: 'reading-u01-l01-q04',
          type: 'multiple-choice',
          prompt: 'In “Bees cluster near the purple blooms,” what should a reader do if cluster is unfamiliar?',
          choices: [
            { id: 'a', text: 'Guess a word that begins with c' },
            { id: 'b', text: 'Check every letter, blend the parts, and reread the sentence' },
            { id: 'c', text: 'Leave the word out permanently' },
            { id: 'd', text: 'Replace it with gather without looking closely' },
          ],
          correctChoiceId: 'b',
          explanation: 'Checking the letters and rereading supports both accurate word reading and meaning.',
          conceptTag: 'reading-accuracy',
          reviewCardId: 'reading-u01-l01-c1',
        },
        {
          id: 'reading-u01-l01-q05',
          type: 'multiple-choice',
          prompt: 'Which reader is using the most appropriate pace?',
          choices: [
            { id: 'a', text: 'A reader who races and misses key details' },
            { id: 'b', text: 'A reader who pauses after every single word' },
            { id: 'c', text: 'A reader who moves smoothly and slows for a difficult idea' },
            { id: 'd', text: 'A reader who skips the middle of each sentence' },
          ],
          correctChoiceId: 'c',
          explanation: 'An appropriate pace stays smooth while making room for challenging ideas.',
          conceptTag: 'appropriate-pace',
          reviewCardId: 'reading-u01-l01-c2',
        },
        {
          id: 'reading-u01-l01-q06',
          type: 'true-false',
          prompt: 'An appropriate reading rate may change when a text becomes more difficult.',
          choices: [
            { id: 'true', text: 'True — readers may slow down to think' },
            { id: 'false', text: 'False — one speed fits every text' },
          ],
          correctChoiceId: 'true',
          explanation: 'Strong readers adjust their pace to match the text and their understanding.',
          conceptTag: 'appropriate-pace',
          reviewCardId: 'reading-u01-l01-c2',
        },
        {
          id: 'reading-u01-l01-q07',
          type: 'multiple-choice',
          prompt: 'Why might a reader pause briefly after the comma in “After the storm, the creek ran high”?',
          choices: [
            { id: 'a', text: 'The comma separates an opening idea from the main action' },
            { id: 'b', text: 'The comma means the passage is finished' },
            { id: 'c', text: 'The comma tells the reader to skip the next word' },
            { id: 'd', text: 'The comma changes creek into a question' },
          ],
          correctChoiceId: 'a',
          explanation: 'A brief comma pause helps the two meaningful parts of the sentence stay clear.',
          conceptTag: 'appropriate-pace',
          reviewCardId: 'reading-u01-l01-c2',
        },
        {
          id: 'reading-u01-l01-q08',
          type: 'multiple-choice',
          prompt: 'A reader forgets the beginning of each sentence before reaching the end; what adjustment may help?',
          choices: [
            { id: 'a', text: 'Read in meaningful word groups at a slightly steadier pace' },
            { id: 'b', text: 'Stop for a long break after every word' },
            { id: 'c', text: 'Read only the first and last words' },
            { id: 'd', text: 'Ignore all punctuation marks' },
          ],
          correctChoiceId: 'a',
          explanation: 'Meaningful word groups help ideas stay connected in the reader’s mind.',
          conceptTag: 'appropriate-pace',
          reviewCardId: 'reading-u01-l01-c2',
        },
        {
          id: 'reading-u01-l01-q09',
          type: 'true-false',
          prompt: 'Silent reading can be fluent even though no one hears the reader’s voice.',
          choices: [
            { id: 'true', text: 'True — accuracy, pace, and meaning also matter silently' },
            { id: 'false', text: 'False — fluency exists only in spoken reading' },
          ],
          correctChoiceId: 'true',
          explanation: 'The standard includes both oral and silent reading with accuracy and an appropriate rate.',
          conceptTag: 'fluency-self-check',
          reviewCardId: 'reading-u01-l01-c3',
        },
        {
          id: 'reading-u01-l01-q10',
          type: 'multiple-choice',
          prompt: 'Which question best checks whether fluent reading supported comprehension?',
          choices: [
            { id: 'a', text: 'How many seconds did I use?' },
            { id: 'b', text: 'Can I explain the main event and point to evidence?' },
            { id: 'c', text: 'Did I finish before everyone else?' },
            { id: 'd', text: 'Was every sentence the same length?' },
          ],
          correctChoiceId: 'b',
          explanation: 'Explaining an idea and citing evidence shows that the words built meaning.',
          conceptTag: 'fluency-self-check',
          reviewCardId: 'reading-u01-l01-c3',
        },
        {
          id: 'reading-u01-l01-q11',
          type: 'multiple-choice',
          prompt: 'Read: “Muddy paw prints crossed the porch, but the dog bed was empty”; which inference uses text evidence?',
          choices: [
            { id: 'a', text: 'The dog may have gone outside because the bed is empty and paw prints cross the porch' },
            { id: 'b', text: 'The dog won a blue ribbon because ribbons are exciting' },
            { id: 'c', text: 'The porch was built yesterday because wood is useful' },
            { id: 'd', text: 'The weather is snowy because winter can be cold' },
          ],
          correctChoiceId: 'a',
          explanation: 'The empty bed and muddy paw prints support the inference that the dog went outside.',
          conceptTag: 'fluency-self-check',
          reviewCardId: 'reading-u01-l01-c3',
        },
        {
          id: 'reading-u01-l01-q12',
          type: 'multiple-choice',
          prompt: 'Which reflection follows the lesson’s clear three-part format?',
          choices: [
            { id: 'a', text: 'Accuracy: corrected one word; Pace: slowed at a long sentence; Meaning/Evidence: explained the egret’s action' },
            { id: 'b', text: 'I read something and it was fine' },
            { id: 'c', text: 'Fast, faster, fastest' },
            { id: 'd', text: 'No labels and no evidence from the text' },
          ],
          correctChoiceId: 'a',
          explanation: 'The labeled accuracy, pace, and meaning notes create organized, evidence-based work.',
          conceptTag: 'fluency-self-check',
          reviewCardId: 'reading-u01-l01-c3',
        },
        {
          id: 'reading-u01-l01-q13',
          type: 'true-false',
          prompt: 'During optional partner practice, active listening means waiting, listening carefully, and giving specific feedback after the reader finishes.',
          choices: [
            { id: 'true', text: 'True — careful listening supports useful feedback' },
            { id: 'false', text: 'False — interrupting often is more helpful' },
          ],
          correctChoiceId: 'true',
          explanation: 'Active listeners attend to the whole reading before sharing a specific observation.',
          conceptTag: 'fluency-self-check',
          reviewCardId: 'reading-u01-l01-c3',
        },
      ],
    },
  },
  {
    id: 'reading-u01-l02',
    unitId: 'reading-u01',
    title: 'Read with Expression and Intonation',
    indicatorCodes: ['ELA.4.F.4.2'],
    intro: [
      { speaker: 'winnie', pose: 'talk', text: 'Accurate words and an appropriate pace create a strong base for fluent reading.' },
      { speaker: 'winnie', pose: 'think', text: 'Expression adds feeling and emphasis that fit the author’s meaning.' },
      { speaker: 'winnie', pose: 'talk', text: 'Intonation is the way a voice rises and falls across a sentence.' },
      { speaker: 'winnie', pose: 'cheer', text: 'Let’s use punctuation and text evidence to make meaning easier to hear and understand.' },
    ],
    learnCards: [
      {
        id: 'reading-u01-l02-c1',
        title: 'Expression reveals meaning',
        blocks: [
          { kind: 'text', text: 'Expression is not simply being loud; it means changing emphasis, tone, or volume to match the ideas and feelings in a text.' },
          { kind: 'example', text: 'In “At last, the lantern glowed,” emphasizing at last can show relief after a long wait.' },
          { kind: 'tip', text: 'Infer a speaker’s feeling from details, then cite the words that guided your voice choice.' },
        ],
      },
      {
        id: 'reading-u01-l02-c2',
        title: 'Intonation follows ideas and punctuation',
        blocks: [
          { kind: 'text', text: 'Intonation is the rise and fall of the voice. A question may rise, a completed statement usually settles, and punctuation helps group ideas.' },
          { kind: 'example', text: 'Compare “You found the trail?” with “You found the trail!”; the same words carry different meanings when punctuation and intonation change.' },
          { kind: 'tip', text: 'Let commas create brief pauses, but use the sentence meaning—not a rigid timer—to decide how the line should sound.' },
        ],
      },
      {
        id: 'reading-u01-l02-c3',
        title: 'Practice, listen, and reflect',
        blocks: [
          { kind: 'text', text: 'Practice with varied academic and personal texts, both orally and silently, and gradually extend how long you read with attention.' },
          { kind: 'text', text: 'For print, oral, visual, digital, or interactive texts, connect captions, images, audio, and written words before choosing an expressive reading.' },
          { kind: 'example', text: 'Preview a line, infer its feeling, read it accurately at an appropriate pace, and then explain how one text clue shaped your expression.' },
          { kind: 'tip', text: 'Use the accepted reflection format Text clue → Voice choice → Meaning connection so your reasoning is clear and complete.' },
          { kind: 'tip', text: 'You may read independently, record yourself for your own review, or ask a partner to listen actively and respond after your turn; the app does not grade a voice recording or provide live collaboration.' },
        ],
      },
    ],
    workedExample: {
      title: 'Give the lighthouse scene a meaningful voice',
      steps: [
        'Read the original lines: “Is that the harbor light?” Tomas asked. A golden blink answered through the fog. “We found the way!”',
        'Use rising intonation for the question because Tomas is uncertain and looking for an answer.',
        'Read the middle statement steadily, with a slight pause after blink, to let the hopeful image become clear.',
        'Use brighter expression on “We found the way!” because the exclamation and the golden light show relief and excitement.',
      ],
    },
    quiz: {
      passThreshold: 8,
      pool: [
        {
          id: 'reading-u01-l02-q01',
          type: 'multiple-choice',
          prompt: 'Which voice best fits “Did the tiny seed sprout?”',
          choices: [
            { id: 'a', text: 'A curious voice that rises with the question' },
            { id: 'b', text: 'A flat voice that ignores the question mark' },
            { id: 'c', text: 'A shouting voice on every word' },
            { id: 'd', text: 'A silent pause instead of the sentence' },
          ],
          correctChoiceId: 'a',
          explanation: 'A curious rising voice matches the question and helps listeners follow its meaning.',
          conceptTag: 'expression-and-meaning',
          reviewCardId: 'reading-u01-l02-c1',
        },
        {
          id: 'reading-u01-l02-q02',
          type: 'multiple-choice',
          prompt: 'What is the main job of expression during fluent reading?',
          choices: [
            { id: 'a', text: 'To make every line louder than the last' },
            { id: 'b', text: 'To match emphasis and tone to the text’s meaning' },
            { id: 'c', text: 'To hide mistakes by changing the voice' },
            { id: 'd', text: 'To replace accurate word reading' },
          ],
          correctChoiceId: 'b',
          explanation: 'Expression supports meaning by matching the ideas and feelings in the text.',
          conceptTag: 'expression-and-meaning',
          reviewCardId: 'reading-u01-l02-c1',
        },
        {
          id: 'reading-u01-l02-q03',
          type: 'true-false',
          prompt: 'Reading every sentence with the same tone always makes the meaning clear.',
          choices: [
            { id: 'true', text: 'True — one tone fits every idea' },
            { id: 'false', text: 'False — tone should respond to meaning' },
          ],
          correctChoiceId: 'false',
          explanation: 'Different ideas and feelings often call for different emphasis and tone.',
          conceptTag: 'expression-and-meaning',
          reviewCardId: 'reading-u01-l02-c1',
        },
        {
          id: 'reading-u01-l02-q04',
          type: 'multiple-choice',
          prompt: 'Read “The missing paddle was here all along!”; which expression best fits?',
          choices: [
            { id: 'a', text: 'Surprise and relief, with emphasis on here' },
            { id: 'b', text: 'Boredom, with a long stop after every word' },
            { id: 'c', text: 'Confusion, while skipping missing' },
            { id: 'd', text: 'Anger, because every exclamation means anger' },
          ],
          correctChoiceId: 'a',
          explanation: 'The discovery and exclamation support a surprised, relieved reading.',
          conceptTag: 'expression-and-meaning',
          reviewCardId: 'reading-u01-l02-c1',
        },
        {
          id: 'reading-u01-l02-q05',
          type: 'multiple-choice',
          prompt: 'In “I wanted the green notebook, not the blue one,” which word should receive useful emphasis?',
          choices: [
            { id: 'a', text: 'Green, because it shows the important contrast' },
            { id: 'b', text: 'The, because articles always carry the message' },
            { id: 'c', text: 'Notebook, because every noun must be shouted' },
            { id: 'd', text: 'I, because the first word is always strongest' },
          ],
          correctChoiceId: 'a',
          explanation: 'Emphasizing green makes its contrast with blue clear.',
          conceptTag: 'expression-and-meaning',
          reviewCardId: 'reading-u01-l02-c1',
        },
        {
          id: 'reading-u01-l02-q06',
          type: 'multiple-choice',
          prompt: 'What does a period usually signal at the end of a statement?',
          choices: [
            { id: 'a', text: 'The voice can settle because the idea is complete' },
            { id: 'b', text: 'The voice must rise like a question' },
            { id: 'c', text: 'The final word should be omitted' },
            { id: 'd', text: 'The sentence should restart immediately' },
          ],
          correctChoiceId: 'a',
          explanation: 'A period marks a completed statement, so the voice usually settles.',
          conceptTag: 'intonation-and-punctuation',
          reviewCardId: 'reading-u01-l02-c2',
        },
        {
          id: 'reading-u01-l02-q07',
          type: 'multiple-choice',
          prompt: 'Which reading best matches “You packed the compass?”',
          choices: [
            { id: 'a', text: 'Let the voice rise to show a question or uncertainty' },
            { id: 'b', text: 'Let the voice drop as if giving a command' },
            { id: 'c', text: 'Pause after each letter in compass' },
            { id: 'd', text: 'Ignore the question mark and rush onward' },
          ],
          correctChoiceId: 'a',
          explanation: 'Rising intonation fits the question mark and the speaker’s uncertainty.',
          conceptTag: 'intonation-and-punctuation',
          reviewCardId: 'reading-u01-l02-c2',
        },
        {
          id: 'reading-u01-l02-q08',
          type: 'multiple-choice',
          prompt: 'What is intonation?',
          choices: [
            { id: 'a', text: 'The rise and fall of the voice across ideas' },
            { id: 'b', text: 'The number of pages in a text' },
            { id: 'c', text: 'The spelling of an unfamiliar word' },
            { id: 'd', text: 'The speed of turning pages' },
          ],
          correctChoiceId: 'a',
          explanation: 'Intonation is the pattern of the voice rising and falling as meaning develops.',
          conceptTag: 'intonation-and-punctuation',
          reviewCardId: 'reading-u01-l02-c2',
        },
        {
          id: 'reading-u01-l02-q09',
          type: 'true-false',
          prompt: 'A comma can suggest a brief pause, but sentence meaning also guides the voice.',
          choices: [
            { id: 'true', text: 'True — punctuation and meaning work together' },
            { id: 'false', text: 'False — commas require the same timed pause everywhere' },
          ],
          correctChoiceId: 'true',
          explanation: 'A comma groups ideas, while the whole sentence determines the most meaningful phrasing.',
          conceptTag: 'intonation-and-punctuation',
          reviewCardId: 'reading-u01-l02-c2',
        },
        {
          id: 'reading-u01-l02-q10',
          type: 'multiple-choice',
          prompt: 'Which practice sequence best supports expressive fluency?',
          choices: [
            { id: 'a', text: 'Preview meaning, choose text evidence, read accurately, then reflect' },
            { id: 'b', text: 'Start shouting, skip hard words, and stop without thinking' },
            { id: 'c', text: 'Count words only and ignore the message' },
            { id: 'd', text: 'Memorize punctuation names instead of reading the passage' },
          ],
          correctChoiceId: 'a',
          explanation: 'Meaning, evidence, accuracy, and reflection work together in fluent practice.',
          conceptTag: 'expressive-practice',
          reviewCardId: 'reading-u01-l02-c3',
        },
        {
          id: 'reading-u01-l02-q11',
          type: 'multiple-choice',
          prompt: 'Read “Lena’s hands shook, but she smiled as the curtain opened”; which voice choice is best supported?',
          choices: [
            { id: 'a', text: 'A mix of nervousness and excitement because she shakes but smiles' },
            { id: 'b', text: 'Sleepiness because curtains are used at night' },
            { id: 'c', text: 'Anger because the sentence contains the word but' },
            { id: 'd', text: 'No feeling because the sentence has no exclamation mark' },
          ],
          correctChoiceId: 'a',
          explanation: 'Her shaking hands and smile support an inference of nervous excitement.',
          conceptTag: 'expressive-practice',
          reviewCardId: 'reading-u01-l02-c3',
        },
        {
          id: 'reading-u01-l02-q12',
          type: 'multiple-choice',
          prompt: 'During optional partner practice, which response shows active listening?',
          choices: [
            { id: 'a', text: 'Wait until the reading ends, then name one text clue the voice made clear' },
            { id: 'b', text: 'Interrupt each sentence to take over the reading' },
            { id: 'c', text: 'Look away and give a score without evidence' },
            { id: 'd', text: 'Change the passage while the partner is reading' },
          ],
          correctChoiceId: 'a',
          explanation: 'Active listening supports specific feedback connected to the text.',
          conceptTag: 'expressive-practice',
          reviewCardId: 'reading-u01-l02-c3',
        },
        {
          id: 'reading-u01-l02-q13',
          type: 'true-false',
          prompt: 'The reflection format Text clue → Voice choice → Meaning connection helps explain and justify an expressive reading.',
          choices: [
            { id: 'true', text: 'True — the format links evidence, choice, and meaning' },
            { id: 'false', text: 'False — quality reflection should omit text evidence' },
          ],
          correctChoiceId: 'true',
          explanation: 'The format creates clear work by connecting a voice decision to evidence and meaning.',
          conceptTag: 'expressive-practice',
          reviewCardId: 'reading-u01-l02-c3',
        },
      ],
    },
  },
] satisfies Lesson[];
