import type { Lesson } from '../schema';

export const unit01Lessons = [
  {
    id: 'reading-u01-l01',
    unitId: 'reading-u01',
    title: 'Read Accurately at a Good Pace',
    indicatorCodes: ['ELA.4.F.4.2'],
    intro: [
      { speaker: 'winnie', pose: 'talk', text: 'Fluent reading begins with getting the words right and understanding what they say.' },
      { speaker: 'winnie', pose: 'think', text: 'A useful pace is not a race; it gives your brain time to build meaning.' },
      { speaker: 'winnie', pose: 'talk', text: 'You can practice fluency while reading aloud or silently.' },
      { speaker: 'winnie', pose: 'cheer', text: 'Let’s combine accuracy, an appropriate pace, expression, and intonation so the message stays clear.' },
    ],
    learnCards: [
      {
        id: 'reading-u01-l01-c1',
        title: 'Accuracy protects the meaning',
        blocks: [
          { kind: 'text', text: 'Fluent readers read the words the author wrote. They notice a mistake, return to it, and reread the sentence so it makes sense.' },
          { kind: 'example', text: 'In “The tiny crab slipped under the striped shell,” changing crab to cap would change the picture, so an accurate reader checks the letters and rereads.' },
          { kind: 'tip', text: 'Use the sentence meaning and every letter in a word; do not guess from only the first sound.' },
        ],
      },
      {
        id: 'reading-u01-l01-c2',
        title: 'An appropriate pace fits the text',
        blocks: [
          { kind: 'text', text: 'Appropriate rate means reading smoothly enough to connect ideas while slowing down for challenging words, important details, or complex sentences.' },
          { kind: 'example', text: 'A reader might move steadily through “Rain tapped the roof,” then pause to unpack a sentence explaining how a rain gauge works.' },
          { kind: 'tip', text: 'Read meaningful groups of words instead of racing word by word or stopping after every word.' },
        ],
      },
      {
        id: 'reading-u01-l01-c3',
        title: 'Check fluency by checking meaning',
        blocks: [
          { kind: 'text', text: 'Build stamina by reading varied academic and personal texts aloud and silently for longer stretches, then explain what you understood.' },
          { kind: 'text', text: 'Written, oral, visual, digital, and interactive texts may combine words with maps, captions, images, or audio, so connect each part to the same message.' },
          { kind: 'example', text: 'After reading “Muddy paw prints crossed the porch, but the dog bed was empty,” infer what may have happened and cite “muddy paw prints” as evidence.' },
          { kind: 'tip', text: 'Use a three-line reflection labeled Accuracy, Pace, and Meaning/Evidence; this consistent format helps you create careful work.' },
          { kind: 'tip', text: 'For optional partner practice, take turns and listen actively before sharing one specific place that sounded clear; this lesson does not score anyone’s spoken reading.' },
        ],
      },
    ],
    workedExample: {
      title: 'Fluency check at the marsh boardwalk',
      steps: [
        'Preview the original passage: “Nia stepped onto the boardwalk. Beyond the reeds, a white egret lifted one wing, balanced, and dipped its beak into the shining water.”',
        'Read accurately by checking boardwalk, egret, and balanced instead of replacing them with easier-looking words.',
        'Use a steady pace, pause briefly at the comma, and slow down enough to picture the egret’s actions.',
        'Check comprehension by inferring that the egret may be drinking or searching for food, then cite its dipping beak as evidence.',
      ],
    },
    quiz: {
      passThreshold: 8,
      pool: [
        {
          id: 'reading-u01-l01-q01',
          type: 'multiple-choice',
          prompt: 'A reader says “girl” instead of “gull” in “The gull glided above the pier”; what should the reader do to protect accuracy?',
          choices: [
            { id: 'a', text: 'Keep going because both words begin with g' },
            { id: 'b', text: 'Check every letter in gull, correct the word, and reread the sentence' },
            { id: 'c', text: 'Guess another g word without looking at the ending' },
            { id: 'd', text: 'Skip the entire sentence and read the next one' },
          ],
          correctChoiceId: 'b',
          explanation: 'Checking every letter and rereading corrects the word so the sentence keeps its meaning.',
          conceptTag: 'reading-accuracy',
          reviewCardId: 'reading-u01-l01-c1',
        },
        {
          id: 'reading-u01-l01-q02',
          type: 'multiple-choice',
          prompt: 'A reader says “cost” instead of “coast”; which fluency skill needs attention?',
          choices: [
            { id: 'a', text: 'Accuracy' },
            { id: 'b', text: 'Volume' },
            { id: 'c', text: 'Page turning' },
            { id: 'd', text: 'Memorization' },
          ],
          correctChoiceId: 'a',
          explanation: 'Replacing coast with cost changes the word and can change the meaning.',
          conceptTag: 'reading-accuracy',
          reviewCardId: 'reading-u01-l01-c1',
        },
        {
          id: 'reading-u01-l01-q03',
          type: 'true-false',
          prompt: 'If a sentence stops making sense, rereading it accurately is a useful strategy.',
          choices: [
            { id: 'true', text: 'True — rereading can repair meaning' },
            { id: 'false', text: 'False — keep going without checking' },
          ],
          correctChoiceId: 'true',
          explanation: 'Rereading lets you correct a word and rebuild the sentence’s meaning.',
          conceptTag: 'reading-accuracy',
          reviewCardId: 'reading-u01-l01-c1',
        },
        {
          id: 'reading-u01-l01-q04',
          type: 'multiple-choice',
          prompt: 'In “Bees cluster near the purple blooms,” what should a reader do if cluster is unfamiliar?',
          choices: [
            { id: 'a', text: 'Guess a word that begins with c' },
            { id: 'b', text: 'Check every letter, blend the parts, and reread the sentence' },
            { id: 'c', text: 'Leave the word out permanently' },
            { id: 'd', text: 'Replace it with gather without looking closely' },
          ],
          correctChoiceId: 'b',
          explanation: 'Checking the letters and rereading supports both accurate word reading and meaning.',
          conceptTag: 'reading-accuracy',
          reviewCardId: 'reading-u01-l01-c1',
        },
        {
          id: 'reading-u01-l01-q05',
          type: 'multiple-choice',
          prompt: 'Which reader is using the most appropriate pace?',
          choices: [
            { id: 'a', text: 'A reader who races and misses key details' },
            { id: 'b', text: 'A reader who pauses after every single word' },
            { id: 'c', text: 'A reader who moves smoothly and slows for a difficult idea' },
            { id: 'd', text: 'A reader who skips the middle of each sentence' },
          ],
          correctChoiceId: 'c',
          explanation: 'An appropriate pace stays smooth while making room for challenging ideas.',
          conceptTag: 'appropriate-pace',
          reviewCardId: 'reading-u01-l01-c2',
        },
        {
          id: 'reading-u01-l01-q06',
          type: 'true-false',
          prompt: 'An appropriate reading rate may change when a text becomes more difficult.',
          choices: [
            { id: 'true', text: 'True — readers may slow down to think' },
            { id: 'false', text: 'False — one speed fits every text' },
          ],
          correctChoiceId: 'true',
          explanation: 'Strong readers adjust their pace to match the text and their understanding.',
          conceptTag: 'appropriate-pace',
          reviewCardId: 'reading-u01-l01-c2',
        },
        {
          id: 'reading-u01-l01-q07',
          type: 'multiple-choice',
          prompt: 'Why might a reader pause briefly after the comma in “After the storm, the creek ran high”?',
          choices: [
            { id: 'a', text: 'The comma separates an opening idea from the main action' },
            { id: 'b', text: 'The comma means the passage is finished' },
            { id: 'c', text: 'The comma tells the reader to skip the next word' },
            { id: 'd', text: 'The comma changes creek into a question' },
          ],
          correctChoiceId: 'a',
          explanation: 'A brief comma pause helps the two meaningful parts of the sentence stay clear.',
          conceptTag: 'appropriate-pace',
          reviewCardId: 'reading-u01-l01-c2',
        },
        {
          id: 'reading-u01-l01-q08',
          type: 'multiple-choice',
          prompt: 'A reader forgets the beginning of each sentence before reaching the end; what adjustment may help?',
          choices: [
            { id: 'a', text: 'Read in meaningful word groups at a slightly steadier pace' },
            { id: 'b', text: 'Stop for a long break after every word' },
            { id: 'c', text: 'Read only the first and last words' },
            { id: 'd', text: 'Ignore all punctuation marks' },
          ],
          correctChoiceId: 'a',
          explanation: 'Meaningful word groups help ideas stay connected in the reader’s mind.',
          conceptTag: 'appropriate-pace',
          reviewCardId: 'reading-u01-l01-c2',
        },
        {
          id: 'reading-u01-l01-q09',
          type: 'true-false',
          prompt: 'Read this passage: “Nia stepped onto the boardwalk. Beyond the reeds, a white egret lifted one wing, balanced, and dipped its beak into the shining water.” True or false: a reader can pause after “boardwalk” because the first sentence ends there.',
          choices: [
            { id: 'true', text: 'True — that pause separates the complete first sentence' },
            { id: 'false', text: 'False — punctuation should never affect pace' },
          ],
          correctChoiceId: 'true',
          explanation: 'The period after “boardwalk” closes the first sentence, so a brief pause helps the meaning stay clear.',
          conceptTag: 'fluency-self-check',
          reviewCardId: 'reading-u01-l01-c3',
        },
        {
          id: 'reading-u01-l01-q10',
          type: 'multiple-choice',
          prompt: 'Read this passage: “Nia stepped onto the boardwalk. Beyond the reeds, a white egret lifted one wing, balanced, and dipped its beak into the shining water.” What does the egret do after it lifts one wing?',
          choices: [
            { id: 'a', text: 'It flies above the reeds and disappears' },
            { id: 'b', text: 'It balances and dips its beak into the shining water' },
            { id: 'c', text: 'It walks back to Nia on the boardwalk' },
            { id: 'd', text: 'It closes both wings and falls asleep' },
          ],
          correctChoiceId: 'b',
          explanation: 'The passage says the egret balances and then dips its beak into the shining water.',
          conceptTag: 'fluency-self-check',
          reviewCardId: 'reading-u01-l01-c3',
        },
        {
          id: 'reading-u01-l01-q11',
          type: 'multiple-choice',
          prompt: 'Read this passage: “Nia stepped onto the boardwalk. Beyond the reeds, a white egret lifted one wing, balanced, and dipped its beak into the shining water.” Which inference is best supported by the egret dipping its beak?',
          choices: [
            { id: 'a', text: 'The egret may be drinking or searching for food' },
            { id: 'b', text: 'The egret is building a nest on the boardwalk' },
            { id: 'c', text: 'The egret is hiding because the water is frozen' },
            { id: 'd', text: 'The egret has already flown far beyond the reeds' },
          ],
          correctChoiceId: 'a',
          explanation: 'Dipping a beak into water supports the inference that the egret may be drinking or searching for food.',
          conceptTag: 'fluency-self-check',
          reviewCardId: 'reading-u01-l01-c3',
        },
        {
          id: 'reading-u01-l01-q12',
          type: 'multiple-choice',
          prompt: 'Read this passage: “Nia stepped onto the boardwalk. Beyond the reeds, a white egret lifted one wing, balanced, and dipped its beak into the shining water.” Which reflection uses evidence from the passage?',
          choices: [
            { id: 'a', text: 'I read “egret” as “eagle,” but I did not reread it' },
            { id: 'b', text: 'I raced through the passage without noticing its punctuation' },
            { id: 'c', text: 'I paused at the sentence break and used the dipping beak as evidence of the egret’s action' },
            { id: 'd', text: 'I skipped the last sentence and gave no reason' },
          ],
          correctChoiceId: 'c',
          explanation: 'The reflection names a useful pause and cites the egret’s dipping beak as evidence.',
          conceptTag: 'fluency-self-check',
          reviewCardId: 'reading-u01-l01-c3',
        },
        {
          id: 'reading-u01-l01-q13',
          type: 'true-false',
          prompt: 'During optional partner practice, active listening means waiting, listening carefully, and giving specific feedback after the reader finishes.',
          choices: [
            { id: 'true', text: 'True — careful listening supports useful feedback' },
            { id: 'false', text: 'False — interrupting often is more helpful' },
          ],
          correctChoiceId: 'true',
          explanation: 'Active listeners attend to the whole reading before sharing a specific observation.',
          conceptTag: 'fluency-self-check',
          reviewCardId: 'reading-u01-l01-c3',
        },
      ],
    },
  },
  {
    id: 'reading-u01-l02',
    unitId: 'reading-u01',
    title: 'Read with Expression and Intonation',
    indicatorCodes: ['ELA.4.F.4.2'],
    intro: [
      { speaker: 'winnie', pose: 'talk', text: 'Accurate words and an appropriate pace create a strong base for fluent reading.' },
      { speaker: 'winnie', pose: 'think', text: 'Expression adds feeling and emphasis that fit the author’s meaning.' },
      { speaker: 'winnie', pose: 'talk', text: 'Intonation is the way a voice rises and falls across a sentence.' },
      { speaker: 'winnie', pose: 'cheer', text: 'Let’s use punctuation and text evidence to make meaning easier to hear and understand.' },
    ],
    learnCards: [
      {
        id: 'reading-u01-l02-c1',
        title: 'Expression reveals meaning',
        blocks: [
          { kind: 'text', text: 'Expression is not simply being loud; it means changing emphasis, tone, or volume to match the ideas and feelings in a text.' },
          { kind: 'example', text: 'In “At last, the lantern glowed,” emphasizing at last can show relief after a long wait.' },
          { kind: 'tip', text: 'Infer a speaker’s feeling from details, then cite the words that guided your voice choice.' },
        ],
      },
      {
        id: 'reading-u01-l02-c2',
        title: 'Intonation follows ideas and punctuation',
        blocks: [
          { kind: 'text', text: 'Intonation is the rise and fall of the voice. A question may rise, a completed statement usually settles, and punctuation helps group ideas.' },
          { kind: 'example', text: 'Compare “You found the trail?” with “You found the trail!”; the same words carry different meanings when punctuation and intonation change.' },
          { kind: 'tip', text: 'Let commas create brief pauses, but use the sentence meaning—not a rigid timer—to decide how the line should sound.' },
        ],
      },
      {
        id: 'reading-u01-l02-c3',
        title: 'Practice, listen, and reflect',
        blocks: [
          { kind: 'text', text: 'Practice with varied academic and personal texts, both orally and silently, and gradually extend how long you read with attention.' },
          { kind: 'text', text: 'For print, oral, visual, digital, or interactive texts, connect captions, images, audio, and written words before choosing an expressive reading.' },
          { kind: 'example', text: 'Preview a line, infer its feeling, read it accurately at an appropriate pace, and then explain how one text clue shaped your expression.' },
          { kind: 'tip', text: 'Use the accepted reflection format Text clue → Voice choice → Meaning connection so your reasoning is clear and complete.' },
          { kind: 'tip', text: 'You may read independently, record yourself for your own review, or ask a partner to listen actively and respond after your turn; the app does not grade a voice recording or provide live collaboration.' },
        ],
      },
    ],
    workedExample: {
      title: 'Give the lighthouse scene a meaningful voice',
      steps: [
        'Read the original lines: “Is that the harbor light?” Tomas asked. A golden blink answered through the fog. “We found the way!”',
        'Use rising intonation for the question because Tomas is uncertain and looking for an answer.',
        'Read the middle statement steadily, with a slight pause after blink, to let the hopeful image become clear.',
        'Use brighter expression on “We found the way!” because the exclamation and the golden light show relief and excitement.',
      ],
    },
    quiz: {
      passThreshold: 8,
      pool: [
        {
          id: 'reading-u01-l02-q01',
          type: 'multiple-choice',
          prompt: 'Read this passage: “Is that the harbor light?” Tomas asked. A golden blink answered through the fog. “We found the way!” Which voice best fits Tomas’s first line?',
          choices: [
            { id: 'a', text: 'A flat voice that ignores the question mark' },
            { id: 'b', text: 'A shouting voice on every word' },
            { id: 'c', text: 'A curious voice that rises with the question' },
            { id: 'd', text: 'A silent pause instead of the sentence' },
          ],
          correctChoiceId: 'c',
          explanation: 'A curious rising voice matches the question and helps listeners follow its meaning.',
          conceptTag: 'intonation-and-punctuation',
          reviewCardId: 'reading-u01-l02-c2',
        },
        {
          id: 'reading-u01-l02-q02',
          type: 'multiple-choice',
          prompt: 'Read this passage: “Is that the harbor light?” Tomas asked. A golden blink answered through the fog. “We found the way!” Which line should sound brightest and most relieved?',
          choices: [
            { id: 'a', text: '“Is that the harbor light?” with quiet uncertainty' },
            { id: 'b', text: '“We found the way!” with bright, excited relief' },
            { id: 'c', text: '“A golden blink answered through the fog” in a rushed monotone' },
            { id: 'd', text: '“Tomas asked” as an angry shout' },
          ],
          correctChoiceId: 'b',
          explanation: 'The exclamation and discovery show relief and excitement in “We found the way!”',
          conceptTag: 'expression-and-meaning',
          reviewCardId: 'reading-u01-l02-c1',
        },
        {
          id: 'reading-u01-l02-q03',
          type: 'true-false',
          prompt: 'Reading every sentence with the same tone always makes the meaning clear.',
          choices: [
            { id: 'true', text: 'True — one tone fits every idea' },
            { id: 'false', text: 'False — tone should respond to meaning' },
          ],
          correctChoiceId: 'false',
          explanation: 'Different ideas and feelings often call for different emphasis and tone.',
          conceptTag: 'expression-and-meaning',
          reviewCardId: 'reading-u01-l02-c1',
        },
        {
          id: 'reading-u01-l02-q04',
          type: 'multiple-choice',
          prompt: 'Read “The missing paddle was here all along!”; which expression best fits?',
          choices: [
            { id: 'a', text: 'Boredom, with a long stop after every word' },
            { id: 'b', text: 'Confusion, while skipping missing' },
            { id: 'c', text: 'Anger, because every exclamation means anger' },
            { id: 'd', text: 'Surprise and relief, with emphasis on here' },
          ],
          correctChoiceId: 'd',
          explanation: 'The discovery and exclamation support a surprised, relieved reading.',
          conceptTag: 'expression-and-meaning',
          reviewCardId: 'reading-u01-l02-c1',
        },
        {
          id: 'reading-u01-l02-q05',
          type: 'multiple-choice',
          prompt: 'In “I wanted the green notebook, not the blue one,” which word should receive useful emphasis?',
          choices: [
            { id: 'a', text: 'The, because articles always carry the message' },
            { id: 'b', text: 'Green, because it shows the important contrast' },
            { id: 'c', text: 'Notebook, because every noun must be shouted' },
            { id: 'd', text: 'I, because the first word is always strongest' },
          ],
          correctChoiceId: 'b',
          explanation: 'Emphasizing green makes its contrast with blue clear.',
          conceptTag: 'expression-and-meaning',
          reviewCardId: 'reading-u01-l02-c1',
        },
        {
          id: 'reading-u01-l02-q06',
          type: 'multiple-choice',
          prompt: 'What does a period usually signal at the end of a statement?',
          choices: [
            { id: 'a', text: 'The voice can settle because the idea is complete' },
            { id: 'b', text: 'The voice must rise like a question' },
            { id: 'c', text: 'The final word should be omitted' },
            { id: 'd', text: 'The sentence should restart immediately' },
          ],
          correctChoiceId: 'a',
          explanation: 'A period marks a completed statement, so the voice usually settles.',
          conceptTag: 'intonation-and-punctuation',
          reviewCardId: 'reading-u01-l02-c2',
        },
        {
          id: 'reading-u01-l02-q07',
          type: 'multiple-choice',
          prompt: 'Which reading best matches “You packed the compass?”',
          choices: [
            { id: 'a', text: 'Let the voice drop as if giving a command' },
            { id: 'b', text: 'Pause after each letter in compass' },
            { id: 'c', text: 'Let the voice rise to show a question or uncertainty' },
            { id: 'd', text: 'Ignore the question mark and rush onward' },
          ],
          correctChoiceId: 'c',
          explanation: 'Rising intonation fits the question mark and the speaker’s uncertainty.',
          conceptTag: 'intonation-and-punctuation',
          reviewCardId: 'reading-u01-l02-c2',
        },
        {
          id: 'reading-u01-l02-q08',
          type: 'multiple-choice',
          prompt: 'What is intonation?',
          choices: [
            { id: 'a', text: 'The number of pages in a text' },
            { id: 'b', text: 'The rise and fall of the voice across ideas' },
            { id: 'c', text: 'The spelling of an unfamiliar word' },
            { id: 'd', text: 'The speed of turning pages' },
          ],
          correctChoiceId: 'b',
          explanation: 'Intonation is the pattern of the voice rising and falling as meaning develops.',
          conceptTag: 'intonation-and-punctuation',
          reviewCardId: 'reading-u01-l02-c2',
        },
        {
          id: 'reading-u01-l02-q09',
          type: 'true-false',
          prompt: 'A comma can suggest a brief pause, but sentence meaning also guides the voice.',
          choices: [
            { id: 'true', text: 'True — punctuation and meaning work together' },
            { id: 'false', text: 'False — commas require the same timed pause everywhere' },
          ],
          correctChoiceId: 'true',
          explanation: 'A comma groups ideas, while the whole sentence determines the most meaningful phrasing.',
          conceptTag: 'intonation-and-punctuation',
          reviewCardId: 'reading-u01-l02-c2',
        },
        {
          id: 'reading-u01-l02-q10',
          type: 'multiple-choice',
          prompt: 'Read this passage: “Is that the harbor light?” Tomas asked. A golden blink answered through the fog. “We found the way!” Which practice sequence best supports expressive fluency in this passage?',
          choices: [
            { id: 'a', text: 'Read every line in a flat voice and ignore the punctuation' },
            { id: 'b', text: 'Make the question and final exclamation sound exactly alike' },
            { id: 'c', text: 'Skip the dialogue and read only the sentence about the fog' },
            { id: 'd', text: 'Read with expression and intonation: raise the question, read the middle steadily, brighten the final line, and explain the text clues' },
          ],
          correctChoiceId: 'd',
          explanation: 'The punctuation and hopeful details guide three different voice choices, followed by an evidence-based reflection.',
          conceptTag: 'expressive-practice',
          reviewCardId: 'reading-u01-l02-c3',
        },
        {
          id: 'reading-u01-l02-q11',
          type: 'multiple-choice',
          prompt: 'Read this passage: “Is that the harbor light?” Tomas asked. A golden blink answered through the fog. “We found the way!” What feeling should Tomas’s final line convey?',
          choices: [
            { id: 'a', text: 'Sleepiness because the fog is quiet' },
            { id: 'b', text: 'Anger because Tomas asked a question first' },
            { id: 'c', text: 'Relief and excitement because the light helped them find the way' },
            { id: 'd', text: 'No feeling because the final line should be flat' },
          ],
          correctChoiceId: 'c',
          explanation: 'The golden light answers Tomas’s uncertainty, and the exclamation shows relief and excitement.',
          conceptTag: 'expressive-practice',
          reviewCardId: 'reading-u01-l02-c3',
        },
        {
          id: 'reading-u01-l02-q12',
          type: 'multiple-choice',
          prompt: 'During optional partner practice, which response shows active listening?',
          choices: [
            { id: 'a', text: 'Interrupt each sentence to take over the reading' },
            { id: 'b', text: 'Wait until the reading ends, then name one text clue the voice made clear' },
            { id: 'c', text: 'Look away and give a score without evidence' },
            { id: 'd', text: 'Change the passage while the partner is reading' },
          ],
          correctChoiceId: 'b',
          explanation: 'Active listening supports specific feedback connected to the text.',
          conceptTag: 'expressive-practice',
          reviewCardId: 'reading-u01-l02-c3',
        },
        {
          id: 'reading-u01-l02-q13',
          type: 'true-false',
          prompt: 'The reflection format Text clue → Voice choice → Meaning connection helps explain and justify an expressive reading.',
          choices: [
            { id: 'true', text: 'True — the format links evidence, choice, and meaning' },
            { id: 'false', text: 'False — quality reflection should omit text evidence' },
          ],
          correctChoiceId: 'true',
          explanation: 'The format creates clear work by connecting a voice decision to evidence and meaning.',
          conceptTag: 'expressive-practice',
          reviewCardId: 'reading-u01-l02-c3',
        },
      ],
    },
  },
] satisfies Lesson[];
