import type { Lesson } from '../schema';

export const unit01Lessons = [
  {
    id: 'science-u01-l01',
    unitId: 'science-u01',
    title: "Speed and an Object's Energy",
    indicatorCodes: ['4-PS3-1'],
    intro: [
      { speaker: 'sandy', pose: 'talk', text: 'A rolling shell can move slowly at first and more quickly later.' },
      { speaker: 'sandy', pose: 'think', text: 'What can its speed tell us about its energy of motion?' },
      { speaker: 'sandy', pose: 'talk', text: 'We will compare the same moving object so our evidence answers that question fairly.' },
      { speaker: 'sandy', pose: 'cheer', text: 'Let’s use careful observations to connect speed and energy!' },
    ],
    learnCards: [
      {
        id: 'science-u01-l01-c1',
        title: 'Describe speed with observations',
        blocks: [
          { kind: 'text', text: 'Speed describes how quickly an object changes position. At this level, words such as slower, faster, and stopped are enough to compare motion.' },
          { kind: 'example', text: 'On the same short path, a toy turtle that reaches the finish first is moving faster than one that arrives later.' },
          { kind: 'tip', text: 'Describe what you can observe instead of inventing an exact measurement.' },
        ],
      },
      {
        id: 'science-u01-l01-c2',
        title: 'Make a fair speed comparison',
        blocks: [
          { kind: 'text', text: 'A fair comparison keeps the object and the path the same while its speed changes. Then the observation can help answer how speed relates to that object’s energy.' },
          { kind: 'example', text: 'Compare the same marble rolling slowly and then faster along the same smooth lane, not a marble on one lane with a sponge ball on another.' },
          { kind: 'tip', text: 'Across unlike objects, speed alone does not tell the whole energy story, so choose the same object or another suitable fair comparison.' },
        ],
      },
      {
        id: 'science-u01-l01-c3',
        title: 'Relate faster motion to more energy',
        blocks: [
          { kind: 'text', text: 'When the same object moves faster, it has more energy of motion than when it moves slower. When it slows, its energy of motion decreases.' },
          { kind: 'example', text: 'The same rolling ball nudges a paper cup a little when moving slowly and nudges it more when moving faster; that difference can be qualitative evidence of more energy of motion.' },
          { kind: 'tip', text: 'State the relationship as more or less energy of motion, without assigning an exact energy value.' },
        ],
      },
    ],
    workedExample: {
      title: 'Compare two trips of the same cart',
      steps: [
        'Jalen observes the same toy cart travel along the same clear path twice.',
        'On the second trip, the cart reaches the end sooner and moves a paper flag farther than on the first trip.',
        'The observations show that the cart was faster on the second trip and had more energy of motion than the same cart on its slower trip.',
      ],
    },
    quiz: {
      passThreshold: 8,
      pool: [
        {
          id: 'science-u01-l01-q01',
          type: 'multiple-choice',
          prompt: 'Two trips use the same toy boat and the same path; on which trip is the boat faster?',
          choices: [
            { id: 'a', text: 'The trip that reaches the end sooner' },
            { id: 'b', text: 'The trip that begins later in the day' },
            { id: 'c', text: 'The trip beside a different-colored marker' },
            { id: 'd', text: 'The trip watched by more people' },
          ],
          correctChoiceId: 'a',
          explanation: 'On the same path, reaching the end sooner is evidence that the boat moved faster.',
          conceptTag: 'qualitative-speed',
          reviewCardId: 'science-u01-l01-c1',
        },
        {
          id: 'science-u01-l01-q02',
          type: 'multiple-choice',
          prompt: 'Which pair of words gives a useful qualitative speed comparison?',
          choices: [
            { id: 'a', text: 'Shiny and dull' },
            { id: 'b', text: 'Slower and faster' },
            { id: 'c', text: 'Round and square' },
            { id: 'd', text: 'Warm and cool' },
          ],
          correctChoiceId: 'b',
          explanation: 'Slower and faster compare how quickly objects change position.',
          conceptTag: 'qualitative-speed',
          reviewCardId: 'science-u01-l01-c1',
        },
        {
          id: 'science-u01-l01-q03',
          type: 'multiple-choice',
          prompt: 'Which observation best describes a cart slowing down?',
          choices: [
            { id: 'a', text: 'Its color becomes easier to see' },
            { id: 'b', text: 'Its wheels stay the same size' },
            { id: 'c', text: 'It covers less of the path during similar moments' },
            { id: 'd', text: 'Its label points toward the ceiling' },
          ],
          correctChoiceId: 'c',
          explanation: 'Covering less of the path during similar moments is qualitative evidence of slower motion.',
          conceptTag: 'qualitative-speed',
          reviewCardId: 'science-u01-l01-c1',
        },
        {
          id: 'science-u01-l01-q04',
          type: 'multiple-choice',
          prompt: 'Which comparison best isolates the relationship between speed and energy of motion?',
          choices: [
            { id: 'a', text: 'A foam ball on carpet and a metal ball on tile' },
            { id: 'b', text: 'A large cart outdoors and a small bead indoors' },
            { id: 'c', text: 'A marble rolling and a block resting' },
            { id: 'd', text: 'The same cart moving slower and faster on the same path' },
          ],
          correctChoiceId: 'd',
          explanation: 'Keeping the cart and path the same makes speed the main changed condition.',
          conceptTag: 'fair-speed-comparison',
          reviewCardId: 'science-u01-l01-c2',
        },
        {
          id: 'science-u01-l01-q05',
          type: 'multiple-choice',
          prompt: 'Why is comparing the same rolling ball at two speeds useful?',
          choices: [
            { id: 'a', text: 'It keeps the object the same while speed changes' },
            { id: 'b', text: 'It guarantees that every surface is different' },
            { id: 'c', text: 'It changes both size and material at once' },
            { id: 'd', text: 'It makes observations unnecessary' },
          ],
          correctChoiceId: 'a',
          explanation: 'A same-object comparison helps connect a change in speed to a change in that object’s energy of motion.',
          conceptTag: 'fair-speed-comparison',
          reviewCardId: 'science-u01-l01-c2',
        },
        {
          id: 'science-u01-l01-q06',
          type: 'multiple-choice',
          prompt: 'Which comparison would need more information before using speed to compare energy?',
          choices: [
            { id: 'a', text: 'The same marble moving slowly and faster' },
            { id: 'b', text: 'A light foam ball and a heavy cart moving at different speeds' },
            { id: 'c', text: 'The same toy turtle on the same lane twice' },
            { id: 'd', text: 'The same cart before and after it slows' },
          ],
          correctChoiceId: 'b',
          explanation: 'Unlike objects differ in more than speed, so speed alone does not make this a fair energy comparison.',
          conceptTag: 'fair-speed-comparison',
          reviewCardId: 'science-u01-l01-c2',
        },
        {
          id: 'science-u01-l01-q07',
          type: 'multiple-choice',
          prompt: 'The same cart moves faster on its second trip; how does its energy of motion compare?',
          choices: [
            { id: 'a', text: 'It has no energy of motion' },
            { id: 'b', text: 'It has exactly the same energy of motion' },
            { id: 'c', text: 'It has more energy of motion' },
            { id: 'd', text: 'Its energy cannot be described at all' },
          ],
          correctChoiceId: 'c',
          explanation: 'The same object has more energy of motion when it moves faster.',
          conceptTag: 'speed-energy-relationship',
          reviewCardId: 'science-u01-l01-c3',
        },
        {
          id: 'science-u01-l01-q08',
          type: 'multiple-choice',
          prompt: 'The same ball slows as it rolls across grass; what happens to its energy of motion?',
          choices: [
            { id: 'a', text: 'It becomes an exact value that must be computed' },
            { id: 'b', text: 'It increases because grass is green' },
            { id: 'c', text: 'It stays greater than on every earlier moment' },
            { id: 'd', text: 'It decreases as the ball slows' },
          ],
          correctChoiceId: 'd',
          explanation: 'As the same ball slows, it has less energy of motion.',
          conceptTag: 'speed-energy-relationship',
          reviewCardId: 'science-u01-l01-c3',
        },
        {
          id: 'science-u01-l01-q09',
          type: 'true-false',
          prompt: 'For the same moving object, faster motion means more energy of motion than slower motion.',
          choices: [
            { id: 'true', text: 'True — this is the qualitative relationship' },
            { id: 'false', text: 'False — speed and energy are never related' },
          ],
          correctChoiceId: 'true',
          explanation: 'A faster-moving version of the same object has more energy of motion.',
          conceptTag: 'speed-energy-relationship',
          reviewCardId: 'science-u01-l01-c3',
        },
        {
          id: 'science-u01-l01-q10',
          type: 'multiple-choice',
          prompt: 'Which statement uses evidence without claiming an exact energy value?',
          choices: [
            { id: 'a', text: 'The faster trip moved the paper flag farther, supporting that the same cart had more energy of motion' },
            { id: 'b', text: 'The cart had a secret exact energy value that no one observed' },
            { id: 'c', text: 'Every object with the same speed always has identical energy' },
            { id: 'd', text: 'The cart’s color proves how quickly it moved' },
          ],
          correctChoiceId: 'a',
          explanation: 'The changed flag motion is an observation that supports a qualitative energy comparison.',
          conceptTag: 'speed-energy-relationship',
          reviewCardId: 'science-u01-l01-c3',
        },
        {
          id: 'science-u01-l01-q11',
          type: 'true-false',
          prompt: 'Speed alone is enough to compare the energy of any two unlike objects.',
          choices: [
            { id: 'true', text: 'True — no other difference matters' },
            { id: 'false', text: 'False — use the same object or another suitable fair comparison' },
          ],
          correctChoiceId: 'false',
          explanation: 'Unlike objects may differ in important ways, so speed alone is not a fair energy comparison.',
          conceptTag: 'fair-speed-comparison',
          reviewCardId: 'science-u01-l01-c2',
        },
        {
          id: 'science-u01-l01-q12',
          type: 'multiple-choice',
          prompt: 'Which conclusion fits a same-cart observation in which the faster trip nudges a flag farther?',
          choices: [
            { id: 'a', text: 'The flag’s color caused the cart to move' },
            { id: 'b', text: 'The faster-moving cart had more energy of motion than the slower-moving cart' },
            { id: 'c', text: 'The slower cart must have had more energy of motion' },
            { id: 'd', text: 'The two trips cannot be compared qualitatively' },
          ],
          correctChoiceId: 'b',
          explanation: 'The same cart’s faster trip and larger observed effect support more energy of motion.',
          conceptTag: 'speed-energy-relationship',
          reviewCardId: 'science-u01-l01-c3',
        },
        {
          id: 'science-u01-l01-q13',
          type: 'true-false',
          prompt: 'Words such as faster, slower, more, and less can describe the speed-energy relationship without exact measurements.',
          choices: [
            { id: 'true', text: 'True — qualitative comparisons use descriptive relationships' },
            { id: 'false', text: 'False — only exact values can support a comparison' },
          ],
          correctChoiceId: 'true',
          explanation: 'Qualitative evidence can relate speed and energy with comparison words.',
          conceptTag: 'qualitative-speed',
          reviewCardId: 'science-u01-l01-c1',
        },
      ],
    },
  },
  {
    id: 'science-u01-l02',
    unitId: 'science-u01',
    title: 'Explain Speed and Energy with Evidence',
    indicatorCodes: ['4-PS3-1'],
    intro: [
      { speaker: 'sandy', pose: 'talk', text: 'A strong science explanation is more than a good guess.' },
      { speaker: 'sandy', pose: 'think', text: 'It begins with evidence: observations that can support a claim.' },
      { speaker: 'sandy', pose: 'talk', text: 'Reasoning connects that evidence to what we know about speed and energy of motion.' },
      { speaker: 'sandy', pose: 'cheer', text: 'Let’s build explanations that another scientist can follow!' },
    ],
    learnCards: [
      {
        id: 'science-u01-l02-c1',
        title: 'Choose relevant evidence',
        blocks: [
          { kind: 'text', text: 'Evidence is an observation connected to the question. For speed and energy, useful evidence may describe which trip was faster and what changed when the same object moved at different speeds.' },
          { kind: 'example', text: 'The same toy car reached a marker sooner and bent a paper strip farther on its faster trip; both observations are relevant.' },
          { kind: 'tip', text: 'An object’s color or a student’s favorite trip is not evidence about its speed-energy relationship.' },
        ],
      },
      {
        id: 'science-u01-l02-c2',
        title: 'Use reasoning to connect the ideas',
        blocks: [
          { kind: 'text', text: 'Reasoning explains why the evidence supports the claim. It uses the idea that the same object has more energy of motion when it moves faster.' },
          { kind: 'example', text: 'Because the same car and path were used, the faster trip is a fair comparison; its larger effect supports more energy of motion.' },
          { kind: 'tip', text: 'Reasoning is the bridge between what was observed and what the evidence means.' },
        ],
      },
      {
        id: 'science-u01-l02-c3',
        title: 'Construct a complete explanation',
        blocks: [
          { kind: 'text', text: 'A complete explanation has a claim, relevant evidence, and reasoning. Each part should answer the same question without adding an exact energy amount.' },
          { kind: 'example', text: 'Claim: the same cart had more energy of motion on its faster trip. Evidence: it reached the marker sooner and moved the paper strip farther. Reasoning: for the same object, faster motion means more energy of motion.' },
          { kind: 'tip', text: 'Check that your evidence is observable and your reasoning explains how it supports the claim.' },
        ],
      },
    ],
    workedExample: {
      title: 'Explain the rolling seed-pod observations',
      steps: [
        'Priya observes the same model seed pod roll along the same lane twice; the quicker trip reaches the leaf marker first and shifts a light paper gate farther.',
        'She claims that the pod had more energy of motion on the quicker trip.',
        'She cites both observations as evidence and reasons that, because the object and path stayed the same, the faster motion supports more energy of motion.',
      ],
    },
    quiz: {
      passThreshold: 8,
      pool: [
        {
          id: 'science-u01-l02-q01',
          type: 'multiple-choice',
          prompt: 'Which detail is relevant evidence that the same cart moved faster on its second trip?',
          choices: [
            { id: 'a', text: 'It reached the same marker sooner' },
            { id: 'b', text: 'A student liked the second trip best' },
            { id: 'c', text: 'Its blue stripe looked bright' },
            { id: 'd', text: 'The observer wore green shoes' },
          ],
          correctChoiceId: 'a',
          explanation: 'Reaching the same marker sooner is an observation directly connected to speed.',
          conceptTag: 'relevant-speed-evidence',
          reviewCardId: 'science-u01-l02-c1',
        },
        {
          id: 'science-u01-l02-q02',
          type: 'multiple-choice',
          prompt: 'Which observation is relevant to the same ball’s energy of motion?',
          choices: [
            { id: 'a', text: 'The ball has a star sticker' },
            { id: 'b', text: 'Its faster trip moved the paper gate farther than its slower trip' },
            { id: 'c', text: 'The lane is beside a window' },
            { id: 'd', text: 'The observer prefers round objects' },
          ],
          correctChoiceId: 'b',
          explanation: 'A changed effect during the same ball’s faster trip is relevant qualitative evidence.',
          conceptTag: 'relevant-speed-evidence',
          reviewCardId: 'science-u01-l02-c1',
        },
        {
          id: 'science-u01-l02-q03',
          type: 'multiple-choice',
          prompt: 'Which note is an observation rather than an opinion?',
          choices: [
            { id: 'a', text: 'The slower trip was boring' },
            { id: 'b', text: 'The red cart is the nicest cart' },
            { id: 'c', text: 'The faster trip reached the paper gate first' },
            { id: 'd', text: 'Everyone should enjoy rolling carts' },
          ],
          correctChoiceId: 'c',
          explanation: 'Which trip reached the gate first can be observed, while the other statements are opinions.',
          conceptTag: 'relevant-speed-evidence',
          reviewCardId: 'science-u01-l02-c1',
        },
        {
          id: 'science-u01-l02-q04',
          type: 'multiple-choice',
          prompt: 'Which reasoning best connects a faster same-cart trip to more energy of motion?',
          choices: [
            { id: 'a', text: 'The cart was faster because its stripe was orange' },
            { id: 'b', text: 'The paper gate moved because science is interesting' },
            { id: 'c', text: 'All objects have identical energy whenever they move' },
            { id: 'd', text: 'For the same object, faster motion means more energy of motion' },
          ],
          correctChoiceId: 'd',
          explanation: 'This reasoning states the scientific idea that links the speed evidence to the energy claim.',
          conceptTag: 'evidence-energy-reasoning',
          reviewCardId: 'science-u01-l02-c2',
        },
        {
          id: 'science-u01-l02-q05',
          type: 'multiple-choice',
          prompt: 'Why does keeping the same object and path strengthen the reasoning?',
          choices: [
            { id: 'a', text: 'It makes the two speeds a suitable fair comparison' },
            { id: 'b', text: 'It makes the object’s color determine its energy' },
            { id: 'c', text: 'It removes the need to observe what happens' },
            { id: 'd', text: 'It proves every unlike object behaves identically' },
          ],
          correctChoiceId: 'a',
          explanation: 'Keeping the object and path the same lets the explanation focus on the speed change.',
          conceptTag: 'evidence-energy-reasoning',
          reviewCardId: 'science-u01-l02-c2',
        },
        {
          id: 'science-u01-l02-q06',
          type: 'multiple-choice',
          prompt: 'What job does reasoning do in a science explanation?',
          choices: [
            { id: 'a', text: 'It lists unrelated facts' },
            { id: 'b', text: 'It explains how the evidence supports the claim' },
            { id: 'c', text: 'It replaces evidence with a preference' },
            { id: 'd', text: 'It gives the object a new name' },
          ],
          correctChoiceId: 'b',
          explanation: 'Reasoning tells why the observations count as support for the claim.',
          conceptTag: 'evidence-energy-reasoning',
          reviewCardId: 'science-u01-l02-c2',
        },
        {
          id: 'science-u01-l02-q07',
          type: 'multiple-choice',
          prompt: 'Which sentence is a clear claim for a speed-energy explanation?',
          choices: [
            { id: 'a', text: 'The cart crossed a leaf picture' },
            { id: 'b', text: 'I wonder who drew the lane' },
            { id: 'c', text: 'The same cart had more energy of motion during its faster trip' },
            { id: 'd', text: 'The paper gate was folded before lunch' },
          ],
          correctChoiceId: 'c',
          explanation: 'The sentence directly answers how the same cart’s speed relates to its energy of motion.',
          conceptTag: 'complete-energy-explanation',
          reviewCardId: 'science-u01-l02-c3',
        },
        {
          id: 'science-u01-l02-q08',
          type: 'multiple-choice',
          prompt: 'Which order builds a complete evidence-based explanation?',
          choices: [
            { id: 'a', text: 'Opinion, decoration, unrelated detail' },
            { id: 'b', text: 'Question, title, favorite result' },
            { id: 'c', text: 'Exact energy amount, guess, color' },
            { id: 'd', text: 'Claim, relevant evidence, reasoning' },
          ],
          correctChoiceId: 'd',
          explanation: 'A claim answers the question, evidence supports it, and reasoning connects the two.',
          conceptTag: 'complete-energy-explanation',
          reviewCardId: 'science-u01-l02-c3',
        },
        {
          id: 'science-u01-l02-q09',
          type: 'true-false',
          prompt: 'A useful explanation can compare more and less energy of motion without giving an exact energy amount.',
          choices: [
            { id: 'true', text: 'True — qualitative evidence supports the relationship' },
            { id: 'false', text: 'False — an exact amount is always required' },
          ],
          correctChoiceId: 'true',
          explanation: 'The standard asks for a qualitative evidence-based relationship rather than an exact energy amount.',
          conceptTag: 'complete-energy-explanation',
          reviewCardId: 'science-u01-l02-c3',
        },
        {
          id: 'science-u01-l02-q10',
          type: 'multiple-choice',
          prompt: 'Which evidence best supports the claim that the same pod had more energy of motion on its quicker trip?',
          choices: [
            { id: 'a', text: 'It reached the marker first and shifted the paper gate farther' },
            { id: 'b', text: 'The pod was found near a tree' },
            { id: 'c', text: 'The observer wrote with a pencil' },
            { id: 'd', text: 'The slower trip happened before the quicker trip' },
          ],
          correctChoiceId: 'a',
          explanation: 'Both observations are relevant to the pod’s faster motion and larger effect.',
          conceptTag: 'relevant-speed-evidence',
          reviewCardId: 'science-u01-l02-c1',
        },
        {
          id: 'science-u01-l02-q11',
          type: 'true-false',
          prompt: 'A favorite color is enough evidence to explain a moving object’s energy.',
          choices: [
            { id: 'true', text: 'True — preferences are scientific observations' },
            { id: 'false', text: 'False — evidence must be relevant to speed and energy' },
          ],
          correctChoiceId: 'false',
          explanation: 'Color preference does not show how speed relates to energy of motion.',
          conceptTag: 'relevant-speed-evidence',
          reviewCardId: 'science-u01-l02-c1',
        },
        {
          id: 'science-u01-l02-q12',
          type: 'multiple-choice',
          prompt: 'Which ending adds reasoning to the claim and evidence?',
          choices: [
            { id: 'a', text: 'The cart is my favorite classroom object' },
            { id: 'b', text: 'Because the same cart moved faster, the observations support that it had more energy of motion' },
            { id: 'c', text: 'The lane would look better with stars' },
            { id: 'd', text: 'A different object might have a different name' },
          ],
          correctChoiceId: 'b',
          explanation: 'This sentence links the fair-comparison evidence to the energy claim.',
          conceptTag: 'evidence-energy-reasoning',
          reviewCardId: 'science-u01-l02-c2',
        },
        {
          id: 'science-u01-l02-q13',
          type: 'true-false',
          prompt: 'Evidence and reasoning should both connect to the claim being explained.',
          choices: [
            { id: 'true', text: 'True — all three parts answer the same question' },
            { id: 'false', text: 'False — unrelated details make a claim stronger' },
          ],
          correctChoiceId: 'true',
          explanation: 'A clear explanation keeps its claim, evidence, and reasoning focused on one question.',
          conceptTag: 'complete-energy-explanation',
          reviewCardId: 'science-u01-l02-c3',
        },
      ],
    },
  },
  {
    id: 'science-u01-l03',
    unitId: 'science-u01',
    title: 'Ask Questions About Collisions',
    indicatorCodes: ['4-PS3-3'],
    intro: [
      { speaker: 'sandy', pose: 'talk', text: 'A collision happens when moving objects bump into something.' },
      { speaker: 'sandy', pose: 'think', text: 'After a collision, an object may slow, stop, speed up, or change direction.' },
      { speaker: 'sandy', pose: 'talk', text: 'Testable questions help us investigate how those motion changes relate to changes in energy.' },
      { speaker: 'sandy', pose: 'cheer', text: 'Let’s ask fair questions and make qualitative predictions!' },
    ],
    learnCards: [
      {
        id: 'science-u01-l03-c1',
        title: 'Notice changes during a collision',
        blocks: [
          { kind: 'text', text: 'In a collision, look for changes in speed or direction. A moving object may slow or stop while the object it hits may begin moving.' },
          { kind: 'example', text: 'A rolling toy cart bumps a still cardboard tube; the cart slows and the tube begins to roll.' },
          { kind: 'tip', text: 'Describe what changed before and after the collision, including changes in energy of motion, without assigning exact values.' },
        ],
      },
      {
        id: 'science-u01-l03-c2',
        title: 'Ask a testable collision question',
        blocks: [
          { kind: 'text', text: 'A testable question names something to change and something to observe. Keep other conditions the same so the comparison is fair.' },
          { kind: 'example', text: 'How does changing the starting speed of the same cart affect how the same tube moves after their collision?' },
          { kind: 'tip', text: 'Questions about changes in speed and energy can be investigated; questions about which collision looks coolest cannot.' },
        ],
      },
      {
        id: 'science-u01-l03-c3',
        title: 'Predict a qualitative outcome',
        blocks: [
          { kind: 'text', text: 'A prediction states what you expect to observe and why. It can use faster, slower, farther, more, or less instead of exact amounts.' },
          { kind: 'example', text: 'If the same cart is moving faster before it hits the same tube, I predict the tube will move farther because the faster cart has more energy of motion.' },
          { kind: 'tip', text: 'A prediction is testable when the before-and-after motion can be observed and compared.' },
        ],
      },
    ],
    workedExample: {
      title: 'Plan a question about two colliding carts',
      steps: [
        'Ari plans to roll the same small cart toward the same still cart on the same clear lane, first slowly and then faster.',
        'Ari asks, “How does the moving cart’s starting speed affect the still cart’s motion after the collision?”',
        'Ari predicts that the still cart will move farther after the faster collision because the same moving cart begins with more energy of motion.',
        'The plan compares visible changes in speed and energy while keeping the carts and lane the same.',
      ],
    },
    quiz: {
      passThreshold: 8,
      pool: [
        {
          id: 'science-u01-l03-q01',
          type: 'multiple-choice',
          prompt: 'Which event is a collision?',
          choices: [
            { id: 'a', text: 'A rolling cart bumps a cardboard tube' },
            { id: 'b', text: 'A still cart waits beside a book' },
            { id: 'c', text: 'A student draws two carts on paper' },
            { id: 'd', text: 'A tube rests alone on a shelf' },
          ],
          correctChoiceId: 'a',
          explanation: 'A collision occurs when the moving cart bumps the tube.',
          conceptTag: 'collision-motion-changes',
          reviewCardId: 'science-u01-l03-c1',
        },
        {
          id: 'science-u01-l03-q02',
          type: 'multiple-choice',
          prompt: 'What should an observer compare around a collision?',
          choices: [
            { id: 'a', text: 'The favorite colors of the observers' },
            { id: 'b', text: 'The objects’ motion before and after they bump' },
            { id: 'c', text: 'The number of words in the directions' },
            { id: 'd', text: 'The day each object was made' },
          ],
          correctChoiceId: 'b',
          explanation: 'Before-and-after motion reveals changes in speed or direction during the collision.',
          conceptTag: 'collision-motion-changes',
          reviewCardId: 'science-u01-l03-c1',
        },
        {
          id: 'science-u01-l03-q03',
          type: 'multiple-choice',
          prompt: 'A moving cart hits a still tube; which observation shows a motion change?',
          choices: [
            { id: 'a', text: 'Both objects have labels' },
            { id: 'b', text: 'The lane remains the same color' },
            { id: 'c', text: 'The cart slows and the tube begins moving' },
            { id: 'd', text: 'The observer writes the date' },
          ],
          correctChoiceId: 'c',
          explanation: 'The cart slowing and the tube starting to move are visible changes caused by the collision.',
          conceptTag: 'collision-motion-changes',
          reviewCardId: 'science-u01-l03-c1',
        },
        {
          id: 'science-u01-l03-q04',
          type: 'multiple-choice',
          prompt: 'Which is the best testable question about a collision?',
          choices: [
            { id: 'a', text: 'Why are toy carts fun?' },
            { id: 'b', text: 'Which cart is the prettiest?' },
            { id: 'c', text: 'Who likes collisions most?' },
            { id: 'd', text: 'How does the same cart’s starting speed affect how far the same tube moves after they collide?' },
          ],
          correctChoiceId: 'd',
          explanation: 'This question changes starting speed and names an observable collision outcome.',
          conceptTag: 'testable-collision-questions',
          reviewCardId: 'science-u01-l03-c2',
        },
        {
          id: 'science-u01-l03-q05',
          type: 'multiple-choice',
          prompt: 'In a fair collision comparison, what should change on purpose?',
          choices: [
            { id: 'a', text: 'The starting speed of the same moving cart' },
            { id: 'b', text: 'The cart, lane, tube, and starting speed all at once' },
            { id: 'c', text: 'The observer’s favorite result' },
            { id: 'd', text: 'The names of both objects after each trial' },
          ],
          correctChoiceId: 'a',
          explanation: 'Changing one condition makes it easier to connect starting speed to the observed outcome.',
          conceptTag: 'testable-collision-questions',
          reviewCardId: 'science-u01-l03-c2',
        },
        {
          id: 'science-u01-l03-q06',
          type: 'multiple-choice',
          prompt: 'Which question names an observable change in energy of motion?',
          choices: [
            { id: 'a', text: 'Which cart has the best name?' },
            { id: 'b', text: 'Does the struck cart move farther when the same incoming cart begins faster?' },
            { id: 'c', text: 'Why is rolling always exciting?' },
            { id: 'd', text: 'Which sticker belongs on the lane?' },
          ],
          correctChoiceId: 'b',
          explanation: 'The question connects a speed change to an outcome that can be observed after collision.',
          conceptTag: 'testable-collision-questions',
          reviewCardId: 'science-u01-l03-c2',
        },
        {
          id: 'science-u01-l03-q07',
          type: 'multiple-choice',
          prompt: 'The same cart will hit the same tube, first slowly and then faster; which prediction fits the lesson?',
          choices: [
            { id: 'a', text: 'The tube will change into a cart' },
            { id: 'b', text: 'The lane will choose the outcome' },
            { id: 'c', text: 'The tube may move farther after the faster collision' },
            { id: 'd', text: 'Nothing observable can change in a collision' },
          ],
          correctChoiceId: 'c',
          explanation: 'The same cart has more energy of motion when faster, so farther tube motion is a reasonable prediction.',
          conceptTag: 'qualitative-collision-predictions',
          reviewCardId: 'science-u01-l03-c3',
        },
        {
          id: 'science-u01-l03-q08',
          type: 'multiple-choice',
          prompt: 'Which prediction includes both an expected outcome and a reason?',
          choices: [
            { id: 'a', text: 'The carts might collide' },
            { id: 'b', text: 'I predict something will happen' },
            { id: 'c', text: 'The tube is made of cardboard' },
            { id: 'd', text: 'The tube will move farther after the faster collision because the same incoming cart has more energy of motion' },
          ],
          correctChoiceId: 'd',
          explanation: 'The statement predicts an observable result and connects it to the cart’s energy of motion.',
          conceptTag: 'qualitative-collision-predictions',
          reviewCardId: 'science-u01-l03-c3',
        },
        {
          id: 'science-u01-l03-q09',
          type: 'true-false',
          prompt: 'A qualitative collision prediction may use words such as farther or slower instead of exact amounts.',
          choices: [
            { id: 'true', text: 'True — comparison words can describe expected changes' },
            { id: 'false', text: 'False — every prediction needs an exact number' },
          ],
          correctChoiceId: 'true',
          explanation: 'Qualitative predictions describe expected changes without requiring exact measurements.',
          conceptTag: 'qualitative-collision-predictions',
          reviewCardId: 'science-u01-l03-c3',
        },
        {
          id: 'science-u01-l03-q10',
          type: 'multiple-choice',
          prompt: 'Which before-and-after note is most useful for a collision investigation?',
          choices: [
            { id: 'a', text: 'Before: tube still; after: tube moving and incoming cart slower' },
            { id: 'b', text: 'Before: observer curious; after: observer still curious' },
            { id: 'c', text: 'Before: lane blue; after: lane blue' },
            { id: 'd', text: 'Before: Tuesday; after: later on Tuesday' },
          ],
          correctChoiceId: 'a',
          explanation: 'The note records observable motion changes in both objects during the collision.',
          conceptTag: 'collision-motion-changes',
          reviewCardId: 'science-u01-l03-c1',
        },
        {
          id: 'science-u01-l03-q11',
          type: 'true-false',
          prompt: '“Which collision looks coolest?” is a testable question about changes in speed and energy.',
          choices: [
            { id: 'true', text: 'True — coolest is an observable energy change' },
            { id: 'false', text: 'False — coolest is an opinion, not a defined motion observation' },
          ],
          correctChoiceId: 'false',
          explanation: 'A testable collision question must name a change and an observable motion outcome.',
          conceptTag: 'testable-collision-questions',
          reviewCardId: 'science-u01-l03-c2',
        },
        {
          id: 'science-u01-l03-q12',
          type: 'multiple-choice',
          prompt: 'Which plan makes the fairest comparison of collision outcomes?',
          choices: [
            { id: 'a', text: 'Change both carts and the lane each time' },
            { id: 'b', text: 'Use the same carts and lane while changing the incoming cart’s starting speed' },
            { id: 'c', text: 'Use one trial and choose the hoped-for answer' },
            { id: 'd', text: 'Compare a rolling cart with a falling leaf' },
          ],
          correctChoiceId: 'b',
          explanation: 'Keeping the carts and lane the same focuses the comparison on starting speed.',
          conceptTag: 'testable-collision-questions',
          reviewCardId: 'science-u01-l03-c2',
        },
        {
          id: 'science-u01-l03-q13',
          type: 'true-false',
          prompt: 'A collision can change the speed and energy of motion of the objects involved.',
          choices: [
            { id: 'true', text: 'True — motion may change when objects collide' },
            { id: 'false', text: 'False — collisions never change motion' },
          ],
          correctChoiceId: 'true',
          explanation: 'Objects may slow, stop, or begin moving during a collision, showing changes in energy of motion.',
          conceptTag: 'collision-motion-changes',
          reviewCardId: 'science-u01-l03-c1',
        },
      ],
    },
  },
] satisfies Lesson[];
