import { exact, phase, pin, select, type Experience } from './types';
const formComparisons:Record<string,string>={'narrative-drama':'performable','narrative-poem':'compressed','drama-poem':'stagepoem'};
const formOptions={narrative:'Narrative',drama:'One-scene drama',poem:'Free-verse poem'};
export const forms:Experience={surface:'forms',phases:[
 phase('Align the return moment','Pin the return of the mitten in each version. The details do not have to be identical.',[
 pin('narrative','Narrative return',{discovery:'June found a red mitten under the library bench.',return:'June passed it to him, and his worried face relaxed.'}),pin('drama','Drama return',{return:'[June hands him the mitten. He lets out a long breath.]',speech:"BOY: That's mine!"}),pin('poem','Poem return',{discovery:'one red mitten waits—',return:'an open hand,'})
 ],exact({narrative:'return',drama:'return',poem:'return'}),'The return aligns across the narrator’s action, stage direction, and poem’s open hand.'),
 phase('Mark the structures','Attach each marker to the form containing its actual example.',[
 {...select('paragraph','Paragraph: “June found a red mitten…”',formOptions),excerpt:"June found a red mitten under the library bench."},{...select('speaker',"Speaker label: “BOY: That's mine!”",formOptions),excerpt:"BOY: That's mine!"},{...select('direction','Stage direction: “[June hands him the mitten. He lets out a long breath.]”',formOptions),excerpt:"[June hands him the mitten. He lets out a long breath.]"},{...select('line','Line: “one red mitten waits—”',formOptions),excerpt:"one red mitten waits\u2014"},{...select('stanza','Stanza: the three lines beginning “A searching boy,”',formOptions),excerpt:"A searching boy,  \nan open hand,  \na worry set down."}
 ],exact({paragraph:'narrative',speaker:'drama',direction:'drama',line:'poem',stanza:'poem'}),'Each structural marker is attached to an example in its own form.','Revisit how the speech and action are arranged. Speaker labels and bracketed directions belong to the performance text.'),
 phase('Keep two forms side by side','Choose a pair and explain a structural effect that the pair supports.',[
 select('pair','Forms to compare',{'narrative-drama':'Narrative and drama','narrative-poem':'Narrative and poem','drama-poem':'Drama and poem'}),select('contrast','What the structure adds',{performable:'The narrator tells us his face relaxed; a stage direction makes relief an action to perform.',compressed:'Paragraphs tell the action directly; lines and stanzas compress relief into “a worry set down.”',stagepoem:'The drama supplies a performable long breath; the poem compresses relief into “a worry set down.”',topic:'The mitten topic is what makes each form different.'})
 ],d=>typeof d.pair==='string'&&typeof d.contrast==='string'&&Object.prototype.hasOwnProperty.call(formComparisons,d.pair)&&formComparisons[d.pair]===d.contrast,'You connected structure to how the same moment is presented.')
]};
export const literal:Experience={surface:'literal',phases:[
 phase('Butterflies: original and literal','Select a faithful literal substitute. Pin a context clue and the effect of the original phrase.',[
 select('literal','Replace “a swarm of butterflies filled Noah’s stomach”',{insects:'many insects were inside Noah',nervous:'Noah felt nervous',happy:'Noah had already won the race'}),pin('context','Butterflies context',{hands:'He pressed his shoes against the track and shook out his hands.',step:'Noah lifted his head and took his first quick step.'}),select('effect','Effect of “butterflies”',{anxiety:'A fluttery, anxious feeling before the start',anticipation:'Restless anticipation while waiting to begin',insects:'A picture of real insects he swallowed'})
 ],d=>d.literal==='nervous'&&d.context==='hands'&&['anxiety','anticipation'].includes(String(d.effect)),'The literal copy keeps the nervous feeling; butterflies add a fluttery image.','Revisit the race setting and Noah’s hands. Keep the event the same instead of adding actual insects.'),
 phase('The whistle: original and literal','Try the second substitution and link the original’s effect to the quiet scene.',[
 select('literal','Replace “the whistle sliced through the silence”',{cut:'the whistle cut an object in half',sound:'the whistle suddenly interrupted the quiet',music:'the runners started singing'}),pin('context','Whistle context',{quiet:'Beside him, runners waited without speaking.',hands:'He pressed his shoes against the track and shook out his hands.'}),select('effect','Effect of “sliced”',{sudden:'A sharp sound suddenly breaks the quiet',slow:'A slow sound gradually fades away',cut:'A real cut appears in the air'})
 ],exact({literal:'sound',context:'quiet',effect:'sudden'}),'The original adds a sharp, sudden interruption to the literal sound.'),
 phase('Compare what the original adds','Read the original and both committed literal substitutions.',[select('comparison','Meaning → Context → Reader effect',{adds:'The originals add a fluttery feeling and a sharp interruption while the literal versions keep the same events.',names:'Naming the figures of speech explains everything.',changed:'The literal copies should change what happened.'})],exact({comparison:'adds'}),'You explained what both vivid phrases add beyond the literal events.')
]};
