import { exact, phase, pin, select, type Experience } from './types';
const headings={location:'Place seating where readers have enough light and where bags do not block the walking path.',books:'Offer a small mix of stories, poems, and information books.',care:'Assign a regular time to straighten the books and check that seats and paths remain clear.'};
const findings={path:'Put seats in good light and keep the walking route clear.',choices:'Provide different kinds of books.',routine:'Set a time to tidy books and check seats and paths.',popular:'Poems are every student’s favorite.',increase:'The corner will make everyone read twice as much.'};
export const inquiry:Experience={surface:'inquiry',phases:[
 phase('Build a focused question','Assemble a topic and information needed. You may reopen this task; revised questions need fresh relevance checks.',[
 select('topic','Question topic',{everything:'Everything about school',corner:'A classroom reading corner'}),select('need','Information needed',{setup:'What choices could help us set it up?',ready:'How could we keep it ready for readers?',all:'Everything anyone could ever learn'})
 ],d=>d.topic==='corner'&&['setup','ready'].includes(String(d.need)),'Your question has a topic and a bounded information need.','Revisit the topic. Name which part of a reading corner you want to understand.'),
 phase('Bookmark and collect findings','Pin two different source sentences. Attach an accurate own-words finding to each.',[
 pin('heading1','First heading bookmark',headings),select('finding1','First own-words finding',findings),pin('heading2','Second heading bookmark',headings),select('finding2','Second own-words finding',findings)
 ],(d,all)=>{const allowed=all[0]?.need==='ready'?['location','care']:['location','books','care'];const match:Record<string,string>={location:'path',books:'choices',care:'routine'};return d.heading1!==d.heading2&&allowed.includes(String(d.heading1))&&allowed.includes(String(d.heading2))&&match[String(d.heading1)]===d.finding1&&match[String(d.heading2)]===d.finding2;},'Two relevant source sentences are linked to faithful own-words findings.','Revisit your current question and the source sentence. Keep only findings that answer this inquiry.'),
 phase('Need another source','Move a genuine unanswered question to the other-source pocket and explain why it belongs there.',[
 select('missing','Question for another source',{cost:'How much would the reading corner cost?',favorites:'Which titles do students like best?',care:'When should books be straightened?'}),select('reason','Why another source is needed',{absent:'The notes contain no prices or survey of favorite titles.',infer:'The notes prove which books are most popular.'})
 ],d=>['cost','favorites'].includes(String(d.missing))&&d.reason==='absent','You gathered relevant findings and named information this packet cannot provide.')
]};
export const paperNotes:Record<string,string>={A:'Keep a tray of clean one-sided sheets for rough sketches and practice work.',B:'The classroom door is painted green.',C:'Check whether both sides of a practice sheet can be used before taking a new one.',D:'Count one-sided sheets in the paper bin for a week to see how often this happens.',E:'The class mascot is an otter.',F:'Add a “Clean reverse sides for practice” label to the reuse tray.'};
export const folder:Experience={surface:'folder',phases:[
 phase('Pack the paper-use folder','Needed information: classroom actions that could reduce paper thrown away after one side is used. Place every note; useful investigations have their own tag.',Object.entries(paperNotes).map(([id,text])=>select(id,`Note ${id}: ${text}`,{outside:"Doesn't answer this question",action:'Helps answer — action',investigation:'Helps answer — investigation'})),exact({A:'action',B:'outside',C:'action',D:'investigation',E:'outside',F:'action'}),'The folder keeps A, C, and F as actions and D as investigation; B and E do not answer this question.','Revisit the paper-use question. Counting investigates the problem; it is not proof that waste was reduced.'),
 phase('Attach inclusion and exclusion reasons','Pin an accepted action and an excluded detail. Explain each connection to the question.',[
 pin('include','Accepted note',paperNotes),select('includeReason','Why the accepted note helps',{reuse:'Reusing clean reverse sides gives the paper another use.',pretty:'It is my favorite detail.'}),pin('exclude','Excluded note',paperNotes),select('excludeReason','Why the excluded note does not answer',{appearance:'A door’s color describes appearance, not paper-use actions.',false:'Excluded notes must be false.'})
 ],d=>['A','C','F'].includes(String(d.include))&&d.includeReason==='reuse'&&d.exclude==='B'&&d.excludeReason==='appearance','You explained relevance using the question rather than truth or preference.'),
 phase('Change the question','New question: What does our classroom look like? Reconsider Note B and explain the change.',[
 select('B','Note B under the appearance question',{outside:"Doesn't answer this question",helps:'Helps answer — appearance'}),select('reason','Why B changes groups',{question:'The door’s color is relevant to appearance; relevance depends on the question.',changed:'The note became true only after the question changed.'})
 ],exact({B:'helps',reason:'question'}),'B moves into the new folder because its appearance detail answers the new question.')
]};
export const libraryNotes:Record<string,string>={A:'Story, poetry, and information labels help readers locate a kind of book.',B:'Smooth page turns can help keep pages from tearing.',C:'Each reading circle member gets a turn to describe a favorite part.',D:'A title list helps readers check which shelf holds a book.',E:'A dry place for returned books helps protect the pages.',F:'Readers can leave a short recommendation for someone choosing a book.'};
export const categories={finding:'Finding books',caring:'Caring for books',sharing:'Sharing reading'};
const synthesis={finding:'Labels and a title list help readers locate books.',caring:'Gentle handling and a dry return place help protect pages.',sharing:'Taking turns and leaving recommendations share reading with others.',sequence:'These notes prove what happened first, next, and last.'};
export const clusters:Experience={surface:'clusters',phases:[
 phase('Arrange three clusters','Choose each folder’s shared idea, then move all six notes. Folder order is your choice.',[
 select('label1','Folder 1 name',categories),select('label2','Folder 2 name',categories),select('label3','Folder 3 name',categories),...Object.entries(libraryNotes).map(([id,text])=>select(id,`Note ${id}: ${text}`,{one:'Folder 1',two:'Folder 2',three:'Folder 3'}))
 ],d=>{const labels:Record<string,string>={one:String(d.label1),two:String(d.label2),three:String(d.label3)};const matches:Record<string,string>={A:'finding',D:'finding',B:'caring',E:'caring',C:'sharing',F:'sharing'};return new Set(Object.values(labels)).size===3&&Object.entries(matches).every(([id,category])=>labels[String(d[id])]===category);},'Every note has one primary folder, and each folder groups a shared idea.','Revisit the shared idea, not the note order. Find two notes that belong together.'),
 phase('Build three group statements','Connect both notes in each folder to a statement that their ideas support.',[
 select('one','Folder 1 group statement',synthesis),select('two','Folder 2 group statement',synthesis),select('three','Folder 3 group statement',synthesis)
 ],(d,all)=>d.one===all[0]?.label1&&d.two===all[0]?.label2&&d.three===all[0]?.label3,'Three group statements are supported by the notes inside their folders.'),
 phase('Explain the arrangement','Explain what grouping does. The optional label on the surface is your own reflection and is not graded.',[select('reason','Why these clusters work',{ideas:'Each pair shares a main idea; the groups do not claim a time order.',sequence:'Folder positions prove the order in which events happened.',one:'Every note must have its own unrelated category.'})],exact({reason:'ideas'}),'Your groups turn separate findings into three supported shared ideas.')
]};
export const citation:Experience={surface:'credit',phases:[
 phase('Repair the quotation','The separate draft copies one source sentence without quotation marks. Add the marks and choose an attribution.',[
 {id:'quotation',label:'Quotation draft',kind:'text',options:[],initial:'Labels need checking when books move.'},select('attribution','Quotation attribution',{moss:'Lena Moss writes:',unknown:'An unknown author says:',me:'I invented these words:'})
 ],d=>['“Labels need checking when books move.”','"Labels need checking when books move."'].includes(String(d.quotation))&&d.attribution==='moss','The exact borrowed sentence has quotation boundaries and names Lena Moss.','Revisit the exact words. Show where the quotation begins and ends, and name the supplied author.'),
 phase('Assemble the citation','Build Author — Title — Publisher — Year from the supplied metadata.',[
 select('author','Citation author',{me:'Me',moss:'Lena Moss'}),select('title','Citation title',{shelf:'A Shelf for Every Reader',labels:'The Best Labels'}),select('publisher','Citation publisher',{practice:'Cram All Practice Library',school:'Our School Council'}),select('year','Citation year',{'2025':'2025','2026':'2026',unknown:'Not supplied'})
 ],exact({author:'moss',title:'shelf',publisher:'practice',year:'2026'}),'Lena Moss — A Shelf for Every Reader — Cram All Practice Library — 2026','Revisit the four supplied metadata fields; do not invent a missing detail.'),
 phase('Credit a faithful paraphrase','Compare both draft structures. Attach the same source credit to a faithful paraphrase and explain why.',[
 select('draft','Paraphrase draft',{A:'Draft A: Moss explains that labels and a title list can guide readers to books, and labels may need updating after books are moved.',B:'Draft B: Clear shelf tags help readers find books without looking through every row.'}),select('credit','Credit for the paraphrase',{no:'No credit because wording changed',yes:'Attach the assembled source citation'}),select('reason','Why both forms need credit',{both:'A quotation borrows wording; a paraphrase borrows ideas. Both name the source. Draft B keeps too much of the sentence shape.',different:'Changing a few words removes every need for credit.'})
 ],exact({draft:'A',credit:'yes',reason:'both'}),'You marked borrowed wording and credited both the quotation and the paraphrase.','Revisit Draft A’s new structure and Draft B’s close sentence shape. Borrowed ideas still need credit.')
]};
