import { useState } from 'react';
import { libraryNotes,paperNotes,categories } from './research';
import { Value } from './SourcePacket';
import type { SurfaceProps } from './ReadingSurfaces';
export function ChainSurface(props:SurfaceProps) {
 return <section className="rw-board" aria-label="Source connection board"><h3>{props.activity==='support-chain'?'Evidence → Reason → Claim':props.activity==='two-views-one-event'?'View → Reaction → Story change':'Language → Perspective → Purpose'}</h3>{props.experience.phases.slice(0,-1).map((phase,i)=><article key={phase.title}><h4>{phase.title} · {props.valid[i]?'Connected':'Draft'}</h4><ol className="rw-chain">{[...phase.fields].sort((a,b)=>['evidence','reason','claim'].indexOf(a.id)-['evidence','reason','claim'].indexOf(b.id)).map(field=><li key={field.id}><small>{field.label}</small><p><Value {...props} phase={i} id={field.id}/></p></li>)}</ol></article>)}</section>;
}
export function InquirySurface(props:SurfaceProps) {
 return <section className="rw-board" aria-label="Inquiry notebook"><h3>Question compass</h3><p><Value {...props} phase={0} id="topic"/> → <Value {...props} phase={0} id="need"/></p>{[1,2].map(i=><article key={i}><h4>Finding {i} · {props.valid[1]?'Connected':'Draft — check relevance'}</h4><blockquote><Value {...props} phase={1} id={`heading${i}`}/></blockquote><p>In my words → <Value {...props} phase={1} id={`finding${i}`}/></p></article>)}<article className="rw-other-source"><h4>Need another source</h4><Value {...props} phase={2} id="missing"/></article></section>;
}
export function FolderSurface(props:SurfaceProps) {
 return <section className="rw-board" aria-label="Research folders"><h3>Paper-use question</h3><p>Which <u>classroom actions could reduce paper being thrown away after only one side is used</u>?</p><div className="rw-folders">{[['action','Helps answer — action'],['investigation','Helps answer — investigation'],['outside',"Doesn't answer this question"],['','Not placed yet']].map(([id,title])=><article key={id} className="rw-folder"><h4>{title}</h4>{Object.entries(paperNotes).filter(([key])=>String(props.drafts[0]?.[key]??'')===id).map(([key,text])=><p key={key} className="rw-note"><b>Note {key}</b> {text}</p>)}</article>)}</div>{props.drafts[2]?.B&&<article><h4>Appearance question · {props.valid[2]?'Connected':'Draft'}</h4><p>What does our classroom look like?</p><p className="rw-note"><b>Note B</b> {paperNotes.B}</p><p>Placed in → <Value {...props} phase={2} id="B"/></p></article>}</section>;
}
export function ClusterSurface(props:SurfaceProps) {
 const [label,setLabel]=useState('');const [secondary,setSecondary]=useState('');
 return <section className="rw-board" aria-label="Research clusters"><h3>Arrange shared ideas</h3><div className="rw-folders">{['one','two','three'].map((id,i)=><article className="rw-folder" key={id}><h4>Folder {i+1}: {categories[String(props.drafts[0]?.[`label${i+1}`]) as keyof typeof categories]??'Choose a name'}</h4>{Object.entries(libraryNotes).filter(([key])=>props.drafts[0]?.[key]===id).map(([key,text])=><p className="rw-note" key={key}><b>Note {key}</b> {text}</p>)}<p data-synthesis-state={props.valid[1]?'connected':'draft'}><b>{props.valid[1]?'Connected group statement':props.drafts[1]?.[id]?'Earlier draft — recheck group statement':'Group statement draft'}:</b> <Value {...props} phase={1} id={id}/></p></article>)}</div><article><h4>Notes not placed</h4>{Object.entries(libraryNotes).filter(([key])=>!props.drafts[0]?.[key]).map(([key,text])=><p key={key}><b>Note {key}</b> {text}</p>)}</article><label>Optional own-word category label<input value={label} onChange={e=>setLabel(e.target.value)}/></label><p>Your label is a reflection; it is not automatically graded.</p><label>Optional secondary connection<input value={secondary} onChange={e=>setSecondary(e.target.value)}/></label>{secondary&&<p>Secondary connection retained: {secondary}. Your primary folders remain in place.</p>}</section>;
}
export function CreditSurface(props:SurfaceProps) {
 return <section className="rw-board" aria-label="Source credit drafts"><h3>Separate writing drafts</h3><p>Invented practice publication, not a real publication.</p><article><h4>Quotation · {props.valid[0]?'Connected':'Draft — check boundaries and credit'}</h4><p><Value {...props} phase={0} id="attribution"/></p><p className="rw-quotation">{props.drafts[0]?.quotation||'Labels need checking when books move.'}</p></article><article><h4>Source citation</h4><p className="rw-citation">{['author','title','publisher','year'].map((id,i)=><span key={id}>{i>0?' — ':''}<Value {...props} phase={1} id={id}/></span>)}</p></article><article><h4>Compare paraphrase drafts</h4><p><b>Draft A:</b> Moss explains that labels and a title list can guide readers to books, and labels may need updating after books are moved.</p><p><b>Draft B:</b> Clear shelf tags help readers find books without looking through every row.</p>{props.drafts[2]?.draft&&<p>Selected: Draft {props.drafts[2].draft} · {props.valid[2]?'Connected':'Draft'}</p>}{props.drafts[2]?.credit==='yes'&&<p>Attached credit: {['author','title','publisher','year'].map((id,i)=><span key={id}>{i>0?' — ':''}<Value {...props} phase={1} id={id}/></span>)}</p>}</article></section>;
}
