import { exact, phase, pin, select, type Experience } from './types';
export const weather:Experience={surface:'weather',phases:[
 phase('Pin an amount','Choose an investigation, then pin an exact labeled table record.',[
 select('investigation','Investigate',{timing:'Timing',amount:'Amount',sound:'Described sound'}),pin('detail','Table detail',{noon:'at noon, West 0.9 and East 0.4',morning:'at 8 a.m., West 0.3 and East 0.0'}),select('contribution','Table contribution',{quantity:'Measured amounts in inches',motive:'Why the reporter likes rain',noise:'Exactly how loud the storm was'})
 ],d=>!!d.investigation&&['noon','morning'].includes(String(d.detail))&&d.contribution==='quantity','The labeled table record adds exact amounts in inches.'),
 phase('Pin a location','Use the mapped locations and direction to place the report’s details.',[pin('detail','Map detail',{map:'West Garden is on the left; East Garden is on the right.',caption:"A puddle surrounds the west garden's stepping-stone at noon."}),select('contribution','Map contribution',{location:'Where the gardens are relative to each other',sound:'The actual sound of the storm',time:'The exact minute rain began'})],exact({detail:'map',contribution:'location'}),'The map adds the gardens’ spatial relationship.'),
 phase('Pin described sound','Pin an exact phrase from the supplied transcript. This packet does not supply audio.',[pin('detail','Transcript phrase',{sound:'At the east garden, I heard softer tapping.',breakfast:'The west roof began pattering before breakfast.'}),select('contribution','Transcript contribution',{experience:'The reporter’s described experience',quantity:'An exact measurement in inches',heard:'Audio I heard in the app'})],d=>['sound','breakfast'].includes(String(d.detail))&&d.contribution==='experience','The transcript adds a described experience; it is not an inch measurement.','Revisit the source label. A transcript describes sound; the table gives inches.'),
 phase('Read the connected report','Use the three pins together, then name an inference the packet cannot support.',[select('together','Words say / Display adds / Together',{combine:'The report gives timing; the table gives amounts, the map gives location, and the transcript describes sound.',same:'Every representation gives exactly the same information.'}),select('limit','What cannot be inferred',{noon:'The west garden had 0.9 inch at noon.','no-ratio':'Louder sound means exactly twice as much rain.'})],exact({together:'combine',limit:'no-ratio'}),'You combined amount, location, and described sound while respecting their limits.')
]};
export const lens:Experience={surface:'chains',phases:[
 phase('Text A language chain','Mark two phrases from A, then connect the wording to a viewpoint and purpose.',[
 pin('phrases','Text A evidence',{belief:'I believe our school should put a reading bench beside the library.',request:'Please ask the school council to consider a bench.',topic:'A reading bench provides seating near a place where books are used.'},true),select('perspective','Text A perspective',{supports:'Supports installing a bench',neutral:'Neutral about the planning choices'}),select('purpose','Text A purpose',{topic:'To mention a bench',persuade:'To persuade readers to ask the council to consider a bench',explain:'To describe planning without advocating a choice'})
 ],exact({phrases:['belief','request'],perspective:'supports',purpose:'persuade'}),'A’s belief and request support its advocacy.','Revisit A’s judgments and request. A topic alone does not explain a purpose.'),
 phase('Text B language chain','Mark two phrases from B and build a separate language → perspective → purpose chain.',[
 pin('phrases','Text B evidence',{planning:'Planning begins with the space available and the number of seats needed.',sites:'Different sites have different needs.',belief:'I believe our school should put a reading bench beside the library.'},true),select('perspective','Text B perspective',{supports:'Urges the school to install this bench',neutral:'Neutral about different planning needs'}),select('purpose','Text B purpose',{persuade:'Ask readers to demand a bench',topic:'Name the topic of benches',explain:'Explain considerations before placing a bench'})
 ],exact({phrases:['planning','sites'],perspective:'neutral',purpose:'explain'}),'B’s planning detail explains considerations without a request.'),
 phase('Compare the authors','Read the quoted wording in both retained chains.',[select('comparison','How the wording serves each purpose',{different:'A’s judgments and request advocate consideration; B’s neutral planning details explain what to consider.',pronouns:'Only the pronouns determine purpose.',same:'Because both discuss a bench, they have the same purpose.'})],exact({comparison:'different'}),'You explained how each author’s language carries out a different purpose.')
]};
export const support:Experience={surface:'chains',phases:[
 phase('Shared return place','Pull the claim into your chain, attach a reason, and pin the supporting record.',[
 pin('claim','Claim',{keep:'Our classroom should keep the book-return tray beside the door.',star:'The tray has a yellow star painted on it.'}),pin('reason','First reason',{repeat:'With that care, it is worth keeping.',place:'It gives readers one clear place to leave finished books.'}),pin('evidence','First evidence',{84:'A classroom log recorded 84 returns in the tray during six weeks.',star:'The tray has a yellow star painted on it.'})
 ],exact({claim:'keep',reason:'place',evidence:'84'}),'84 recorded returns support a clear shared return place, supporting the claim.','Revisit how the evidence supports a reason. Repeating the claim does not explain why.'),
 phase('Possible organization benefit','Attach a second reason and its comparison. Keep a limit tag with this evidence.',[
 pin('reason','Second reason',{organization:'The tray may also help the class find returned books.',star:'The tray has a yellow star painted on it.'}),pin('evidence','Second evidence',{counts:'During the week before it was added, six returned books were found on other shelves. In the first week with the tray, two were found elsewhere.',84:'A classroom log recorded 84 returns in the tray during six weeks.'}),select('limit','Limit tag',{proved:'The counts prove the tray caused the change.',different:'The weeks differed, so the counts alone do not prove the tray caused the change.'})
 ],exact({reason:'organization',evidence:'counts',limit:'different'}),'The comparison suggests a possible organization benefit and retains the causal limit.','Revisit the qualification: the weeks differed. Keep that limit attached to the counts.'),
 phase('Park decoration; retain care','Place the two remaining source strips according to their role.',[
 select('decoration','The tray has a yellow star painted on it.',{support:'Evidence of easier returns',aside:'Unrelated decoration'}),select('condition','It must be emptied regularly so it does not overflow.',{aside:'Unrelated decoration',care:'Maintenance condition for keeping the tray'})
 ],exact({decoration:'aside',condition:'care'}),'The star is decoration; regular emptying is a condition, not irrelevant detail.'),
 phase('Explain the support','Follow each retained evidence → reason → claim chain.',[select('reasoning','What the whole argument supports',{qualified:'The records support reasons to keep the tray, with regular emptying and a limit on the before/after comparison.',cause:'The tray certainly caused fewer misplaced books.',star:'The yellow star proves the tray is useful.'})],exact({reasoning:'qualified'}),'Your chains connect evidence to the claim without overstating the source.')
]};
export const views:Experience={surface:'chains',phases:[
 phase('Ari’s beginning chain','Pin the shared event and Ari’s evidence. Link his view to his reaction.',[
 pin('event','Shared event',{rain:'Rain moved the music rehearsal from the courtyard into a small room.',chairs:'Bea helped, and they tried a quieter version of the part together.'}),pin('evidence','Ari evidence',{ari:'“Now no one will hear it properly,” he said.',bea:'“At least the instruments will stay dry.”'}),select('view','Ari viewpoint',{disappointed:'Disappointed that the drum part will not sound as he hoped',relieved:'Relieved to keep the violin dry'}),pin('reaction','Ari reaction',{stopped:'Ari thought her smile meant she did not care about his drum part, so he stopped helping arrange the chairs.',smiled:'Bea smiled and carried her violin inside.'})
 ],exact({event:'rain',evidence:'ari',view:'disappointed',reaction:'stopped'}),'Ari’s disappointment and assumption lead him to stop helping.','Revisit whose words each strip describes; do not add an unsupported motive.'),
 phase('Bea’s view and the turning point','Build Bea’s chain. Mark the exact line that changes Ari’s interpretation.',[
 pin('evidence','Bea evidence',{bea:'“At least the instruments will stay dry.”',ari:'“Now no one will hear it properly,” he said.'}),select('view','Bea viewpoint',{relieved:'Relieved about protecting the instruments',dislike:'Her smile proves she dislikes Ari'}),select('reaction','Bea response',{clarified:'Explains her smile when she notices Ari stop helping',ignored:'Ignores Ari and leaves'}),pin('turn','Turning-point line',{relieved:"I'm relieved about the rain, not happy that you're disappointed.",smile:'Bea smiled and carried her violin inside.'})
 ],exact({evidence:'bea',view:'relieved',reaction:'clarified',turn:'relieved'}),'Bea clarifies her relief, giving Ari a different explanation for her smile.'),
 phase('Compare beginning and ending','Trace the misunderstanding to the characters’ later actions.',[select('effect','How the perspectives shape the story',{cooperate:'Ari’s assumption causes conflict; Bea’s clarification helps them adjust the chairs and cooperate.',same:'The characters never change their interpretation.',dislike:'Bea proves she never cared about Ari’s drum.'})],exact({effect:'cooperate'}),'You connected the different views to conflict and later cooperation.')
]};
