import standardsData from './standards/standards.json';
import { StandardsDataSchema } from './standards/schema';

const standards = StandardsDataSchema.parse(standardsData);

export const READING_OE_CODES: readonly string[] = Object.freeze(
  standards.reading.crossCuttingExpectations.map(({ code }) => code),
);

export type PlannedLesson = {
  id: string;
  unitId: string;
  title: string;
  indicatorCodes: readonly string[];
};

export const PLANNED_LESSONS = [
  { id: 'math-u01-l01', unitId: 'math-u01', title: 'Numbers to the Millions', indicatorCodes: ['4.NR.1.1'] },
  { id: 'math-u01-l02', unitId: 'math-u01', title: 'Comparing and Ordering Big Numbers', indicatorCodes: ['4.NR.1.3'] },
  { id: 'math-u02-l01', unitId: 'math-u02', title: 'Add and Subtract to 100,000', indicatorCodes: ['4.PAFR.1.1'] },
  { id: 'math-u02-l02', unitId: 'math-u02', title: 'Estimate and Judge Reasonableness', indicatorCodes: ['4.NR.1.2'] },
  { id: 'math-u03-l01', unitId: 'math-u03', title: 'Factor Pairs, Primes, and Composites', indicatorCodes: ['4.PAFR.3.1'] },
  { id: 'math-u03-l02', unitId: 'math-u03', title: 'Rules and Function-Table Patterns', indicatorCodes: ['4.PAFR.3.2'] },
  { id: 'math-u04-l01', unitId: 'math-u04', title: 'Multiply by Multiples of 10 and 100', indicatorCodes: ['4.PAFR.1.2'] },
  { id: 'math-u04-l02', unitId: 'math-u04', title: 'Decompose to Multiply Multi-Digit Numbers', indicatorCodes: ['4.PAFR.1.3'] },
  { id: 'math-u04-l03', unitId: 'math-u04', title: 'Multiplicative Comparisons and Unknowns', indicatorCodes: ['4.PAFR.3.3'] },
  { id: 'math-u05-l01', unitId: 'math-u05', title: 'Divide up to Four Digits by One Digit, Including Remainders', indicatorCodes: ['4.PAFR.1.4'] },
  { id: 'math-u05-l02', unitId: 'math-u05', title: 'Two-Step Equations with an Unknown', indicatorCodes: ['4.PAFR.3.4'] },
  { id: 'math-u06-l01', unitId: 'math-u06', title: 'Equivalent Fractions and Models', indicatorCodes: ['4.NR.2.3'] },
  { id: 'math-u06-l02', unitId: 'math-u06', title: 'Compose and Decompose Like-Denominator Fractions', indicatorCodes: ['4.NR.2.4'] },
  { id: 'math-u06-l03', unitId: 'math-u06', title: 'Mixed Numbers and Fractions Greater Than One', indicatorCodes: ['4.NR.2.5'] },
  { id: 'math-u06-l04', unitId: 'math-u06', title: 'Compare Fractions and Mixed Numbers', indicatorCodes: ['4.NR.2.6'] },
  { id: 'math-u07-l01', unitId: 'math-u07', title: 'Add and Subtract Like-Denominator Fractions', indicatorCodes: ['4.PAFR.2.1'] },
  { id: 'math-u07-l02', unitId: 'math-u07', title: 'Whole Number Times a Unit Fraction', indicatorCodes: ['4.PAFR.2.3'] },
  { id: 'math-u07-l03', unitId: 'math-u07', title: 'Fractions as Equal-Sharing Division', indicatorCodes: ['4.PAFR.2.4'] },
  { id: 'math-u08-l01', unitId: 'math-u08', title: 'Tenths and Hundredths as Fractions and Decimals', indicatorCodes: ['4.NR.2.1'] },
  { id: 'math-u08-l02', unitId: 'math-u08', title: 'Compare Decimals with Benchmarks', indicatorCodes: ['4.NR.2.2'] },
  { id: 'math-u08-l03', unitId: 'math-u08', title: 'Add and Subtract Tenths and Hundredths', indicatorCodes: ['4.PAFR.2.2'] },
  { id: 'math-u09-l01', unitId: 'math-u09', title: 'Money Collections and Purchases', indicatorCodes: ['4.MGSR.2.1'] },
  { id: 'math-u09-l02', unitId: 'math-u09', title: 'Elapsed, Start, and End Time', indicatorCodes: ['4.MGSR.2.2'] },
  { id: 'math-u09-l03', unitId: 'math-u09', title: 'Measure to the Nearest Quarter Inch', indicatorCodes: ['4.MGSR.2.3'] },
  { id: 'math-u09-l04', unitId: 'math-u09', title: 'Measure Customary and Metric Weight', indicatorCodes: ['4.MGSR.2.4'] },
  { id: 'math-u09-l05', unitId: 'math-u09', title: 'Convert Larger Customary Units to Smaller Units', indicatorCodes: ['4.MGSR.2.5'] },
  { id: 'math-u10-l01', unitId: 'math-u10', title: 'Rectangle Perimeter and Unknown Sides', indicatorCodes: ['4.MGSR.1.1'] },
  { id: 'math-u10-l02', unitId: 'math-u10', title: 'Rectangle Area in Square Units', indicatorCodes: ['4.MGSR.1.2'] },
  { id: 'math-u11-l01', unitId: 'math-u11', title: 'Classify Triangles by Sides and Angles', indicatorCodes: ['4.MGSR.3.1'] },
  { id: 'math-u11-l02', unitId: 'math-u11', title: 'The Quadrilateral Hierarchy', indicatorCodes: ['4.MGSR.3.2'] },
  { id: 'math-u12-l01', unitId: 'math-u12', title: 'Collect and Organize Data', indicatorCodes: ['4.DPSR.1.1'] },
  { id: 'math-u12-l02', unitId: 'math-u12', title: 'Solve Problems with Graphs and Tables', indicatorCodes: ['4.DPSR.1.2'] },
  { id: 'math-u12-l03', unitId: 'math-u12', title: 'Certain, Possible, and Impossible', indicatorCodes: ['4.DPSR.2.1'] },

  { id: 'reading-u01-l01', unitId: 'reading-u01', title: 'Read Accurately at a Good Pace', indicatorCodes: ['ELA.4.F.4.2'] },
  { id: 'reading-u01-l02', unitId: 'reading-u01', title: 'Read with Expression and Intonation', indicatorCodes: ['ELA.4.F.4.2'] },
  { id: 'reading-u02-l01', unitId: 'reading-u02', title: 'Build Meaning with Roots, Base Words, and Affixes', indicatorCodes: ['ELA.4.AOR.9.1'] },
  { id: 'reading-u02-l02', unitId: 'reading-u02', title: 'Use Definition, Example, and Restatement Clues', indicatorCodes: ['ELA.4.AOR.7.1'] },
  { id: 'reading-u02-l03', unitId: 'reading-u02', title: 'Use Print and Digital References Precisely', indicatorCodes: ['ELA.4.AOR.7.1'] },
  { id: 'reading-u03-l01', unitId: 'reading-u03', title: 'Connect Setting, Conflict, Character Change, and Plot', indicatorCodes: ['ELA.4.AOR.1.1'] },
  { id: 'reading-u04-l01', unitId: 'reading-u04', title: 'Explain Explicit and Implied Themes', indicatorCodes: ['ELA.4.AOR.2.1'] },
  { id: 'reading-u05-l01', unitId: 'reading-u05', title: 'Explain Stated and Implied Central Ideas', indicatorCodes: ['ELA.4.AOR.2.2'] },
  { id: 'reading-u06-l01', unitId: 'reading-u06', title: 'Summarize Literary Texts', indicatorCodes: ['ELA.4.AOR.6.1'] },
  { id: 'reading-u06-l02', unitId: 'reading-u06', title: 'Summarize Informational Texts', indicatorCodes: ['ELA.4.AOR.6.1'] },
  { id: 'reading-u07-l01', unitId: 'reading-u07', title: 'Use Text Features and Informational Structures', indicatorCodes: ['ELA.4.AOR.5.2'] },
  { id: 'reading-u07-l02', unitId: 'reading-u07', title: 'Explain How Visuals and Multimedia Add Meaning', indicatorCodes: ['ELA.4.AOR.10.1'] },
  { id: 'reading-u08-l01', unitId: 'reading-u08', title: "Connect Author's Purpose and Perspective", indicatorCodes: ['ELA.4.AOR.4.1'] },
  { id: 'reading-u08-l02', unitId: 'reading-u08', title: 'Explain Claims, Reasons, and Evidence', indicatorCodes: ['ELA.4.AOR.5.3'] },
  { id: 'reading-u09-l01', unitId: 'reading-u09', title: 'Compare First- and Third-Person Narration', indicatorCodes: ['ELA.4.AOR.3.1'] },
  { id: 'reading-u09-l02', unitId: 'reading-u09', title: 'Explain How Character Perspectives Shape a Story', indicatorCodes: ['ELA.4.AOR.3.1'] },
  { id: 'reading-u10-l01', unitId: 'reading-u10', title: 'Compare Narratives, Dramas, and Poems', indicatorCodes: ['ELA.4.AOR.5.1'] },
  { id: 'reading-u10-l02', unitId: 'reading-u10', title: 'Interpret Literal and Nonliteral Language', indicatorCodes: ['ELA.4.AOR.8.1'] },
  { id: 'reading-u10-l03', unitId: 'reading-u10', title: "Explain Figurative Language's Effect", indicatorCodes: ['ELA.4.AOR.1.2'] },
  { id: 'reading-u11-l01', unitId: 'reading-u11', title: 'Ask an Inquiry Question and Examine a Source', indicatorCodes: ['ELA.4.R.1.1'] },
  { id: 'reading-u11-l02', unitId: 'reading-u11', title: 'Judge the Credibility of a Provided Source', indicatorCodes: ['ELA.4.R.1.2'] },
  { id: 'reading-u11-l03', unitId: 'reading-u11', title: 'Select Information Relevant to a Topic', indicatorCodes: ['ELA.4.R.1.3'] },
  { id: 'reading-u11-l04', unitId: 'reading-u11', title: 'Group Related Research Findings', indicatorCodes: ['ELA.4.R.1.4'] },
  { id: 'reading-u11-l05', unitId: 'reading-u11', title: 'Cite Sources and Avoid Plagiarism', indicatorCodes: ['ELA.4.R.1.5'] },

  { id: 'science-u01-l01', unitId: 'science-u01', title: "Speed and an Object's Energy", indicatorCodes: ['4-PS3-1'] },
  { id: 'science-u01-l02', unitId: 'science-u01', title: 'Explain Speed and Energy with Evidence', indicatorCodes: ['4-PS3-1'] },
  { id: 'science-u01-l03', unitId: 'science-u01', title: 'Ask Questions About Collisions', indicatorCodes: ['4-PS3-3'] },
  { id: 'science-u01-l04', unitId: 'science-u01', title: 'Predict Collision Energy Outcomes', indicatorCodes: ['4-PS3-3'] },
  { id: 'science-u02-l01', unitId: 'science-u02', title: 'Observe Energy Transfer', indicatorCodes: ['4-PS3-2'] },
  { id: 'science-u02-l02', unitId: 'science-u02', title: 'Use Sound and Light as Evidence', indicatorCodes: ['4-PS3-2'] },
  { id: 'science-u02-l03', unitId: 'science-u02', title: 'Use Heat and Electric Current as Evidence', indicatorCodes: ['4-PS3-2'] },
  { id: 'science-u02-l04', unitId: 'science-u02', title: 'Compare Energy Transfer Observations', indicatorCodes: ['4-PS3-2'] },
  { id: 'science-u03-l01', unitId: 'science-u03', title: 'Model Wave Amplitude Patterns', indicatorCodes: ['4-PS4-1'] },
  { id: 'science-u03-l02', unitId: 'science-u03', title: 'Describe Wavelength Patterns', indicatorCodes: ['4-PS4-1'] },
  { id: 'science-u03-l03', unitId: 'science-u03', title: 'Model Waves Moving Objects', indicatorCodes: ['4-PS4-1'] },
  { id: 'science-u03-l04', unitId: 'science-u03', title: 'Model Reflected Light Entering the Eye', indicatorCodes: ['4-PS4-2'] },
  { id: 'science-u04-l01', unitId: 'science-u04', title: 'Build Two-Value Message Patterns', indicatorCodes: ['4-PS4-3'] },
  { id: 'science-u04-l02', unitId: 'science-u04', title: 'Design Morse and Drum Codes', indicatorCodes: ['4-PS4-3'] },
  { id: 'science-u04-l03', unitId: 'science-u04', title: 'Send Binary-Grid Picture Messages', indicatorCodes: ['4-PS4-3'] },
  { id: 'science-u04-l04', unitId: 'science-u04', title: 'Compare Message Solutions', indicatorCodes: ['4-PS4-3'] },
  { id: 'science-u05-l01', unitId: 'science-u05', title: 'Trace Allowed Energy Conversions', indicatorCodes: ['4-PS3-4'] },
  { id: 'science-u05-l02', unitId: 'science-u05', title: 'Plan a Device with Constraints', indicatorCodes: ['4-PS3-4'] },
  { id: 'science-u05-l03', unitId: 'science-u05', title: 'Test an Energy-Conversion Device', indicatorCodes: ['4-PS3-4'] },
  { id: 'science-u05-l04', unitId: 'science-u05', title: 'Refine a Device Using Test Evidence', indicatorCodes: ['4-PS3-4'] },
  { id: 'science-u06-l01', unitId: 'science-u06', title: 'Explain Plant Structures as a System', indicatorCodes: ['4-LS1-1'] },
  { id: 'science-u06-l02', unitId: 'science-u06', title: 'Explain Animal Structures as a System', indicatorCodes: ['4-LS1-1'] },
  { id: 'science-u06-l03', unitId: 'science-u06', title: 'Argue How Structures Support Survival', indicatorCodes: ['4-LS1-1'] },
  { id: 'science-u06-l04', unitId: 'science-u06', title: 'Model Sense, Brain, and Response', indicatorCodes: ['4-LS1-2'] },
  { id: 'science-u07-l01', unitId: 'science-u07', title: 'Find Earth-Feature Patterns on Maps', indicatorCodes: ['4-ESS2-2'] },
  { id: 'science-u07-l02', unitId: 'science-u07', title: 'Interpret Earth-Feature Map Data', indicatorCodes: ['4-ESS2-2'] },
  { id: 'science-u07-l03', unitId: 'science-u07', title: 'Test a Weathering or Erosion Variable', indicatorCodes: ['4-ESS2-1'] },
  { id: 'science-u07-l04', unitId: 'science-u07', title: 'Use Rock Layers and Fossils as Change Evidence', indicatorCodes: ['4-ESS1-1'] },
  { id: 'science-u08-l01', unitId: 'science-u08', title: 'Trace Energy and Fuels to Natural Resources', indicatorCodes: ['4-ESS3-1'] },
  { id: 'science-u08-l02', unitId: 'science-u08', title: 'Explain Environmental Effects of Resource Use', indicatorCodes: ['4-ESS3-1'] },
  { id: 'science-u08-l03', unitId: 'science-u08', title: 'Describe Natural-Process Hazards', indicatorCodes: ['4-ESS3-2'] },
  { id: 'science-u08-l04', unitId: 'science-u08', title: 'Compare Hazard-Impact Solutions', indicatorCodes: ['4-ESS3-2'] },
] as const satisfies readonly PlannedLesson[];
