import { allLessons } from './subjects';

const designedPlacements = [
  [
    "math-u02-l02",
    "math-u02-l02-c3",
    "math-workshop",
    "estimate-checkpoint"
  ],
  [
    "math-u03-l02",
    "math-u03-l02-c2",
    "math-workshop",
    "acorn-rule-machine"
  ],
  [
    "math-u05-l02",
    "math-u05-l02-c2",
    "math-workshop",
    "pack-use-rebuild"
  ],
  [
    "math-u06-l02",
    "math-u06-l02-c3",
    "math-workshop",
    "fraction-picnic"
  ],
  [
    "math-u06-l03",
    "math-u06-l03-c2",
    "math-workshop",
    "bundle-the-fourths"
  ],
  [
    "math-u08-l03",
    "math-u08-l03-c3",
    "math-workshop",
    "decimal-exchange-mat"
  ],
  [
    "math-u10-l01",
    "math-u10-l01-c2",
    "math-workshop",
    "fence-the-garden"
  ],
  [
    "math-u11-l01",
    "math-u11-l01-c3",
    "math-workshop",
    "triangle-inspection-desk"
  ],
  [
    "math-u12-l02",
    "math-u12-l02-c3",
    "math-workshop",
    "graph-detective"
  ],
  [
    "reading-u01-l02",
    "reading-u01-l02-c2",
    "reading-workshop",
    "direct-the-reading"
  ],
  [
    "reading-u02-l03",
    "reading-u02-l03-c3",
    "reading-workshop",
    "word-desk"
  ],
  [
    "reading-u07-l02",
    "reading-u07-l02-c3",
    "reading-workshop",
    "connect-weather-report"
  ],
  [
    "reading-u08-l01",
    "reading-u08-l01-c3",
    "reading-workshop",
    "authors-lens"
  ],
  [
    "reading-u08-l02",
    "reading-u08-l02-c3",
    "reading-workshop",
    "support-chain"
  ],
  [
    "reading-u09-l02",
    "reading-u09-l02-c3",
    "reading-workshop",
    "two-views-one-event"
  ],
  [
    "reading-u10-l01",
    "reading-u10-l01-c3",
    "reading-workshop",
    "one-moment-three-forms"
  ],
  [
    "reading-u10-l03",
    "reading-u10-l03-c3",
    "reading-workshop",
    "literal-and-vivid"
  ],
  [
    "reading-u11-l01",
    "reading-u11-l01-c3",
    "reading-workshop",
    "question-compass"
  ],
  [
    "reading-u11-l03",
    "reading-u11-l03-c3",
    "reading-workshop",
    "research-folder"
  ],
  [
    "reading-u11-l04",
    "reading-u11-l04-c3",
    "reading-workshop",
    "research-clusters"
  ],
  [
    "reading-u11-l05",
    "reading-u11-l05-c3",
    "reading-workshop",
    "source-credit"
  ],
  [
    "science-u02-l04",
    "science-u02-l04-c3",
    "science-workshop",
    "receiver-changes"
  ],
  [
    "science-u03-l02",
    "science-u03-l02-c2",
    "science-workshop",
    "crest-to-crest"
  ],
  [
    "science-u04-l03",
    "science-u04-l03-c3",
    "science-workshop",
    "pixel-post"
  ],
  [
    "science-u04-l04",
    "science-u04-l04-c3",
    "science-workshop",
    "message-design-trials"
  ],
  [
    "science-u05-l03",
    "science-u05-l03-c1",
    "science-workshop",
    "lamp-test-notebook"
  ],
  [
    "science-u06-l01",
    "science-u06-l01-c3",
    "science-workshop",
    "plant-system"
  ],
  [
    "science-u06-l03",
    "science-u06-l03-c3",
    "science-workshop",
    "survival-evidence"
  ],
  [
    "science-u06-l04",
    "science-u06-l04-c3",
    "science-workshop",
    "sense-response"
  ]
];

test.each(designedPlacements)('%s has its exact authored activity at %s', (lessonId, cardId, type, activity) => {
  const lesson = allLessons().find(item => item.id === lessonId);
  const card = lesson?.learnCards.find(item => item.id === cardId);
  expect(card?.widget).toEqual({ type, config: { activity } });
  expect(card?.widgetCoach?.intro.map(line => line.speaker)).toEqual(['guide', 'kid']);
  expect(card?.widgetCoach?.startLabel).toBeTruthy();
  expect(card?.widgetCoach?.reactions.complete.text).toBeTruthy();
});
